// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	json "encoding/json"
	io "io"
	reflect "reflect"

	searchengine "github.com/hmchangw/chat/pkg/searchengine"
	gomock "go.uber.org/mock/gomock"
)

// MockindexStore is a mock of indexStore interface.
type MockindexStore struct {
	ctrl     *gomock.Controller
	recorder *MockindexStoreMockRecorder
	isgomock struct{}
}

// MockindexStoreMockRecorder is the mock recorder for MockindexStore.
type MockindexStoreMockRecorder struct {
	mock *MockindexStore
}

// NewMockindexStore creates a new mock instance.
func NewMockindexStore(ctrl *gomock.Controller) *MockindexStore {
	mock := &MockindexStore{ctrl: ctrl}
	mock.recorder = &MockindexStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockindexStore) EXPECT() *MockindexStoreMockRecorder {
	return m.recorder
}

// Bulk mocks base method.
func (m *MockindexStore) Bulk(ctx context.Context, actions []searchengine.BulkAction) ([]searchengine.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk", ctx, actions)
	ret0, _ := ret[0].([]searchengine.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bulk indicates an expected call of Bulk.
func (mr *MockindexStoreMockRecorder) Bulk(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockindexStore)(nil).Bulk), ctx, actions)
}

// EnsureLifecyclePolicy mocks base method.
func (m *MockindexStore) EnsureLifecyclePolicy(ctx context.Context, name string, body json.RawMessage) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureLifecyclePolicy", ctx, name, body)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EnsureLifecyclePolicy indicates an expected call of EnsureLifecyclePolicy.
func (mr *MockindexStoreMockRecorder) EnsureLifecyclePolicy(ctx, name, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureLifecyclePolicy", reflect.TypeOf((*MockindexStore)(nil).EnsureLifecyclePolicy), ctx, name, body)
}

// GetDoc mocks base method.
func (m *MockindexStore) GetDoc(ctx context.Context, index, docID string) (json.RawMessage, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoc", ctx, index, docID)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDoc indicates an expected call of GetDoc.
func (mr *MockindexStoreMockRecorder) GetDoc(ctx, index, docID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoc", reflect.TypeOf((*MockindexStore)(nil).GetDoc), ctx, index, docID)
}

// UpsertTemplate mocks base method.
func (m *MockindexStore) UpsertTemplate(ctx context.Context, name string, body json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTemplate", ctx, name, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTemplate indicates an expected call of UpsertTemplate.
func (mr *MockindexStoreMockRecorder) UpsertTemplate(ctx, name, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTemplate", reflect.TypeOf((*MockindexStore)(nil).UpsertTemplate), ctx, name, body)
}

// MockobjectStore is a mock of objectStore interface.
type MockobjectStore struct {
	ctrl     *gomock.Controller
	recorder *MockobjectStoreMockRecorder
	isgomock struct{}
}

// MockobjectStoreMockRecorder is the mock recorder for MockobjectStore.
type MockobjectStoreMockRecorder struct {
	mock *MockobjectStore
}

// NewMockobjectStore creates a new mock instance.
func NewMockobjectStore(ctrl *gomock.Controller) *MockobjectStore {
	mock := &MockobjectStore{ctrl: ctrl}
	mock.recorder = &MockobjectStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockobjectStore) EXPECT() *MockobjectStoreMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockobjectStore) Put(ctx context.Context, key string, body io.Reader, size int64, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, key, body, size, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockobjectStoreMockRecorder) Put(ctx, key, body, size, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockobjectStore)(nil).Put), ctx, key, body, size, contentType)
}
