// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	cassandra "github.com/hmchangw/chat/pkg/model/cassandra"
	searchengine "github.com/hmchangw/chat/pkg/searchengine"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageSource is a mock of MessageSource interface.
type MockMessageSource struct {
	ctrl     *gomock.Controller
	recorder *MockMessageSourceMockRecorder
	isgomock struct{}
}

// MockMessageSourceMockRecorder is the mock recorder for MockMessageSource.
type MockMessageSourceMockRecorder struct {
	mock *MockMessageSource
}

// NewMockMessageSource creates a new mock instance.
func NewMockMessageSource(ctrl *gomock.Controller) *MockMessageSource {
	mock := &MockMessageSource{ctrl: ctrl}
	mock.recorder = &MockMessageSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageSource) EXPECT() *MockMessageSourceMockRecorder {
	return m.recorder
}

// StreamMessages mocks base method.
func (m *MockMessageSource) StreamMessages(ctx context.Context, siteID, roomID string, from, to time.Time, fn func(cassandra.Message) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamMessages", ctx, siteID, roomID, from, to, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamMessages indicates an expected call of StreamMessages.
func (mr *MockMessageSourceMockRecorder) StreamMessages(ctx, siteID, roomID, from, to, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamMessages", reflect.TypeOf((*MockMessageSource)(nil).StreamMessages), ctx, siteID, roomID, from, to, fn)
}

// MockSubscriptionSource is a mock of SubscriptionSource interface.
type MockSubscriptionSource struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionSourceMockRecorder
	isgomock struct{}
}

// MockSubscriptionSourceMockRecorder is the mock recorder for MockSubscriptionSource.
type MockSubscriptionSourceMockRecorder struct {
	mock *MockSubscriptionSource
}

// NewMockSubscriptionSource creates a new mock instance.
func NewMockSubscriptionSource(ctrl *gomock.Controller) *MockSubscriptionSource {
	mock := &MockSubscriptionSource{ctrl: ctrl}
	mock.recorder = &MockSubscriptionSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionSource) EXPECT() *MockSubscriptionSourceMockRecorder {
	return m.recorder
}

// RoomIDs mocks base method.
func (m *MockSubscriptionSource) RoomIDs(ctx context.Context, siteID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomIDs", ctx, siteID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomIDs indicates an expected call of RoomIDs.
func (mr *MockSubscriptionSourceMockRecorder) RoomIDs(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomIDs", reflect.TypeOf((*MockSubscriptionSource)(nil).RoomIDs), ctx, siteID)
}

// Subscriptions mocks base method.
func (m *MockSubscriptionSource) Subscriptions(ctx context.Context, siteID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscriptions", ctx, siteID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscriptions indicates an expected call of Subscriptions.
func (mr *MockSubscriptionSourceMockRecorder) Subscriptions(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscriptions", reflect.TypeOf((*MockSubscriptionSource)(nil).Subscriptions), ctx, siteID)
}

// MockESStore is a mock of ESStore interface.
type MockESStore struct {
	ctrl     *gomock.Controller
	recorder *MockESStoreMockRecorder
	isgomock struct{}
}

// MockESStoreMockRecorder is the mock recorder for MockESStore.
type MockESStoreMockRecorder struct {
	mock *MockESStore
}

// NewMockESStore creates a new mock instance.
func NewMockESStore(ctrl *gomock.Controller) *MockESStore {
	mock := &MockESStore{ctrl: ctrl}
	mock.recorder = &MockESStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockESStore) EXPECT() *MockESStoreMockRecorder {
	return m.recorder
}

// Bulk mocks base method.
func (m *MockESStore) Bulk(ctx context.Context, actions []searchengine.BulkAction) ([]searchengine.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk", ctx, actions)
	ret0, _ := ret[0].([]searchengine.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bulk indicates an expected call of Bulk.
func (mr *MockESStoreMockRecorder) Bulk(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockESStore)(nil).Bulk), ctx, actions)
}
