// Code generated by MockGen. DO NOT EDIT.
// Source: bootstrap.go
//
// Generated by this command:
//
//	mockgen -source=bootstrap.go -destination=mock_bootstrap_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTemplateStore is a mock of TemplateStore interface.
type MockTemplateStore struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateStoreMockRecorder
	isgomock struct{}
}

// MockTemplateStoreMockRecorder is the mock recorder for MockTemplateStore.
type MockTemplateStoreMockRecorder struct {
	mock *MockTemplateStore
}

// NewMockTemplateStore creates a new mock instance.
func NewMockTemplateStore(ctrl *gomock.Controller) *MockTemplateStore {
	mock := &MockTemplateStore{ctrl: ctrl}
	mock.recorder = &MockTemplateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateStore) EXPECT() *MockTemplateStoreMockRecorder {
	return m.recorder
}

// PutScript mocks base method.
func (m *MockTemplateStore) PutScript(ctx context.Context, id string, body json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutScript", ctx, id, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutScript indicates an expected call of PutScript.
func (mr *MockTemplateStoreMockRecorder) PutScript(ctx, id, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutScript", reflect.TypeOf((*MockTemplateStore)(nil).PutScript), ctx, id, body)
}

// UpsertTemplate mocks base method.
func (m *MockTemplateStore) UpsertTemplate(ctx context.Context, name string, body json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTemplate", ctx, name, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTemplate indicates an expected call of UpsertTemplate.
func (mr *MockTemplateStoreMockRecorder) UpsertTemplate(ctx, name, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTemplate", reflect.TypeOf((*MockTemplateStore)(nil).UpsertTemplate), ctx, name, body)
}
