// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	msgraph "github.com/hmchangw/chat/pkg/msgraph"
	gomock "go.uber.org/mock/gomock"
)

// MockactiveLister is a mock of activeLister interface.
type MockactiveLister struct {
	ctrl     *gomock.Controller
	recorder *MockactiveListerMockRecorder
	isgomock struct{}
}

// MockactiveListerMockRecorder is the mock recorder for MockactiveLister.
type MockactiveListerMockRecorder struct {
	mock *MockactiveLister
}

// NewMockactiveLister creates a new mock instance.
func NewMockactiveLister(ctrl *gomock.Controller) *MockactiveLister {
	mock := &MockactiveLister{ctrl: ctrl}
	mock.recorder = &MockactiveListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockactiveLister) EXPECT() *MockactiveListerMockRecorder {
	return m.recorder
}

// ActiveAccounts mocks base method.
func (m *MockactiveLister) ActiveAccounts(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveAccounts", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveAccounts indicates an expected call of ActiveAccounts.
func (mr *MockactiveListerMockRecorder) ActiveAccounts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveAccounts", reflect.TypeOf((*MockactiveLister)(nil).ActiveAccounts), ctx)
}

// MockuserResolver is a mock of userResolver interface.
type MockuserResolver struct {
	ctrl     *gomock.Controller
	recorder *MockuserResolverMockRecorder
	isgomock struct{}
}

// MockuserResolverMockRecorder is the mock recorder for MockuserResolver.
type MockuserResolverMockRecorder struct {
	mock *MockuserResolver
}

// NewMockuserResolver creates a new mock instance.
func NewMockuserResolver(ctrl *gomock.Controller) *MockuserResolver {
	mock := &MockuserResolver{ctrl: ctrl}
	mock.recorder = &MockuserResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserResolver) EXPECT() *MockuserResolverMockRecorder {
	return m.recorder
}

// ResolveAccountIDs mocks base method.
func (m *MockuserResolver) ResolveAccountIDs(ctx context.Context, accounts []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAccountIDs", ctx, accounts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAccountIDs indicates an expected call of ResolveAccountIDs.
func (mr *MockuserResolverMockRecorder) ResolveAccountIDs(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAccountIDs", reflect.TypeOf((*MockuserResolver)(nil).ResolveAccountIDs), ctx, accounts)
}

// MockpresenceReader is a mock of presenceReader interface.
type MockpresenceReader struct {
	ctrl     *gomock.Controller
	recorder *MockpresenceReaderMockRecorder
	isgomock struct{}
}

// MockpresenceReaderMockRecorder is the mock recorder for MockpresenceReader.
type MockpresenceReaderMockRecorder struct {
	mock *MockpresenceReader
}

// NewMockpresenceReader creates a new mock instance.
func NewMockpresenceReader(ctrl *gomock.Controller) *MockpresenceReader {
	mock := &MockpresenceReader{ctrl: ctrl}
	mock.recorder = &MockpresenceReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpresenceReader) EXPECT() *MockpresenceReaderMockRecorder {
	return m.recorder
}

// GetPresencesByUserId mocks base method.
func (m *MockpresenceReader) GetPresencesByUserId(ctx context.Context, ids []string) ([]msgraph.Presence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPresencesByUserId", ctx, ids)
	ret0, _ := ret[0].([]msgraph.Presence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresencesByUserId indicates an expected call of GetPresencesByUserId.
func (mr *MockpresenceReaderMockRecorder) GetPresencesByUserId(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPresencesByUserId", reflect.TypeOf((*MockpresenceReader)(nil).GetPresencesByUserId), ctx, ids)
}

// MockexternalApplier is a mock of externalApplier interface.
type MockexternalApplier struct {
	ctrl     *gomock.Controller
	recorder *MockexternalApplierMockRecorder
	isgomock struct{}
}

// MockexternalApplierMockRecorder is the mock recorder for MockexternalApplier.
type MockexternalApplierMockRecorder struct {
	mock *MockexternalApplier
}

// NewMockexternalApplier creates a new mock instance.
func NewMockexternalApplier(ctrl *gomock.Controller) *MockexternalApplier {
	mock := &MockexternalApplier{ctrl: ctrl}
	mock.recorder = &MockexternalApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockexternalApplier) EXPECT() *MockexternalApplierMockRecorder {
	return m.recorder
}

// SetExternal mocks base method.
func (m *MockexternalApplier) SetExternal(ctx context.Context, account string, status model.PresenceStatus, ttl time.Duration) (bool, model.PresenceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExternal", ctx, account, status, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(model.PresenceStatus)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetExternal indicates an expected call of SetExternal.
func (mr *MockexternalApplierMockRecorder) SetExternal(ctx, account, status, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExternal", reflect.TypeOf((*MockexternalApplier)(nil).SetExternal), ctx, account, status, ttl)
}

// MockinCallIndex is a mock of inCallIndex interface.
type MockinCallIndex struct {
	ctrl     *gomock.Controller
	recorder *MockinCallIndexMockRecorder
	isgomock struct{}
}

// MockinCallIndexMockRecorder is the mock recorder for MockinCallIndex.
type MockinCallIndexMockRecorder struct {
	mock *MockinCallIndex
}

// NewMockinCallIndex creates a new mock instance.
func NewMockinCallIndex(ctrl *gomock.Controller) *MockinCallIndex {
	mock := &MockinCallIndex{ctrl: ctrl}
	mock.recorder = &MockinCallIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockinCallIndex) EXPECT() *MockinCallIndexMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockinCallIndex) Add(ctx context.Context, account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockinCallIndexMockRecorder) Add(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockinCallIndex)(nil).Add), ctx, account)
}

// Members mocks base method.
func (m *MockinCallIndex) Members(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Members indicates an expected call of Members.
func (mr *MockinCallIndexMockRecorder) Members(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockinCallIndex)(nil).Members), ctx)
}

// Remove mocks base method.
func (m *MockinCallIndex) Remove(ctx context.Context, account string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockinCallIndexMockRecorder) Remove(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockinCallIndex)(nil).Remove), ctx, account)
}

// MockidMapStore is a mock of idMapStore interface.
type MockidMapStore struct {
	ctrl     *gomock.Controller
	recorder *MockidMapStoreMockRecorder
	isgomock struct{}
}

// MockidMapStoreMockRecorder is the mock recorder for MockidMapStore.
type MockidMapStoreMockRecorder struct {
	mock *MockidMapStore
}

// NewMockidMapStore creates a new mock instance.
func NewMockidMapStore(ctrl *gomock.Controller) *MockidMapStore {
	mock := &MockidMapStore{ctrl: ctrl}
	mock.recorder = &MockidMapStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidMapStore) EXPECT() *MockidMapStoreMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockidMapStore) Resolve(ctx context.Context, accounts []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, accounts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockidMapStoreMockRecorder) Resolve(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockidMapStore)(nil).Resolve), ctx, accounts)
}

// Store mocks base method.
func (m *MockidMapStore) Store(ctx context.Context, mapping map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockidMapStoreMockRecorder) Store(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockidMapStore)(nil).Store), ctx, mapping)
}

// MockstatePublisher is a mock of statePublisher interface.
type MockstatePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockstatePublisherMockRecorder
	isgomock struct{}
}

// MockstatePublisherMockRecorder is the mock recorder for MockstatePublisher.
type MockstatePublisherMockRecorder struct {
	mock *MockstatePublisher
}

// NewMockstatePublisher creates a new mock instance.
func NewMockstatePublisher(ctrl *gomock.Controller) *MockstatePublisher {
	mock := &MockstatePublisher{ctrl: ctrl}
	mock.recorder = &MockstatePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatePublisher) EXPECT() *MockstatePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockstatePublisher) Publish(ctx context.Context, account string, status model.PresenceStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", ctx, account, status)
}

// Publish indicates an expected call of Publish.
func (mr *MockstatePublisherMockRecorder) Publish(ctx, account, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockstatePublisher)(nil).Publish), ctx, account, status)
}
