// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/inbox-worker (interfaces: InboxStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . InboxStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInboxStore is a mock of InboxStore interface.
type MockInboxStore struct {
	ctrl     *gomock.Controller
	recorder *MockInboxStoreMockRecorder
	isgomock struct{}
}

// MockInboxStoreMockRecorder is the mock recorder for MockInboxStore.
type MockInboxStoreMockRecorder struct {
	mock *MockInboxStore
}

// NewMockInboxStore creates a new mock instance.
func NewMockInboxStore(ctrl *gomock.Controller) *MockInboxStore {
	mock := &MockInboxStore{ctrl: ctrl}
	mock.recorder = &MockInboxStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxStore) EXPECT() *MockInboxStoreMockRecorder {
	return m.recorder
}

// AddThreadUnread mocks base method.
func (m *MockInboxStore) AddThreadUnread(ctx context.Context, roomID, parentMessageID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddThreadUnread", ctx, roomID, parentMessageID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddThreadUnread indicates an expected call of AddThreadUnread.
func (mr *MockInboxStoreMockRecorder) AddThreadUnread(ctx, roomID, parentMessageID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddThreadUnread", reflect.TypeOf((*MockInboxStore)(nil).AddThreadUnread), ctx, roomID, parentMessageID, accounts)
}

// ApplySubscriptionRestriction mocks base method.
func (m *MockInboxStore) ApplySubscriptionRestriction(ctx context.Context, roomID string, restricted, externalAccess bool, ownerAccount string, restrictUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySubscriptionRestriction", ctx, roomID, restricted, externalAccess, ownerAccount, restrictUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySubscriptionRestriction indicates an expected call of ApplySubscriptionRestriction.
func (mr *MockInboxStoreMockRecorder) ApplySubscriptionRestriction(ctx, roomID, restricted, externalAccess, ownerAccount, restrictUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySubscriptionRestriction", reflect.TypeOf((*MockInboxStore)(nil).ApplySubscriptionRestriction), ctx, roomID, restricted, externalAccess, ownerAccount, restrictUpdatedAt)
}

// ApplyThreadRead mocks base method.
func (m *MockInboxStore) ApplyThreadRead(ctx context.Context, roomID, threadRoomID, account, parentMessageID string, lastSeenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyThreadRead", ctx, roomID, threadRoomID, account, parentMessageID, lastSeenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyThreadRead indicates an expected call of ApplyThreadRead.
func (mr *MockInboxStoreMockRecorder) ApplyThreadRead(ctx, roomID, threadRoomID, account, parentMessageID, lastSeenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyThreadRead", reflect.TypeOf((*MockInboxStore)(nil).ApplyThreadRead), ctx, roomID, threadRoomID, account, parentMessageID, lastSeenAt)
}

// ApplyThreadReadAll mocks base method.
func (m *MockInboxStore) ApplyThreadReadAll(ctx context.Context, account string, lastSeenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyThreadReadAll", ctx, account, lastSeenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyThreadReadAll indicates an expected call of ApplyThreadReadAll.
func (mr *MockInboxStoreMockRecorder) ApplyThreadReadAll(ctx, account, lastSeenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyThreadReadAll", reflect.TypeOf((*MockInboxStore)(nil).ApplyThreadReadAll), ctx, account, lastSeenAt)
}

// ApplyUserPermissions mocks base method.
func (m *MockInboxStore) ApplyUserPermissions(ctx context.Context, permission model.PermissionKey, accounts []string, state model.PermissionState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyUserPermissions", ctx, permission, accounts, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyUserPermissions indicates an expected call of ApplyUserPermissions.
func (mr *MockInboxStoreMockRecorder) ApplyUserPermissions(ctx, permission, accounts, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyUserPermissions", reflect.TypeOf((*MockInboxStore)(nil).ApplyUserPermissions), ctx, permission, accounts, state)
}

// BulkCreateSubscriptions mocks base method.
func (m *MockInboxStore) BulkCreateSubscriptions(ctx context.Context, subs []*model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateSubscriptions", ctx, subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreateSubscriptions indicates an expected call of BulkCreateSubscriptions.
func (mr *MockInboxStoreMockRecorder) BulkCreateSubscriptions(ctx, subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateSubscriptions", reflect.TypeOf((*MockInboxStore)(nil).BulkCreateSubscriptions), ctx, subs)
}

// BulkRefreshJoinedAt mocks base method.
func (m *MockInboxStore) BulkRefreshJoinedAt(ctx context.Context, roomID string, joinedAtByAccount map[string]time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkRefreshJoinedAt", ctx, roomID, joinedAtByAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkRefreshJoinedAt indicates an expected call of BulkRefreshJoinedAt.
func (mr *MockInboxStoreMockRecorder) BulkRefreshJoinedAt(ctx, roomID, joinedAtByAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkRefreshJoinedAt", reflect.TypeOf((*MockInboxStore)(nil).BulkRefreshJoinedAt), ctx, roomID, joinedAtByAccount)
}

// CreateSubscription mocks base method.
func (m *MockInboxStore) CreateSubscription(ctx context.Context, sub *model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockInboxStoreMockRecorder) CreateSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockInboxStore)(nil).CreateSubscription), ctx, sub)
}

// DeleteRemoteRoomActivity mocks base method.
func (m *MockInboxStore) DeleteRemoteRoomActivity(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRemoteRoomActivity", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRemoteRoomActivity indicates an expected call of DeleteRemoteRoomActivity.
func (mr *MockInboxStoreMockRecorder) DeleteRemoteRoomActivity(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRemoteRoomActivity", reflect.TypeOf((*MockInboxStore)(nil).DeleteRemoteRoomActivity), ctx, roomID)
}

// DeleteSubscriptionsByAccounts mocks base method.
func (m *MockInboxStore) DeleteSubscriptionsByAccounts(ctx context.Context, roomID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionsByAccounts", ctx, roomID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionsByAccounts indicates an expected call of DeleteSubscriptionsByAccounts.
func (mr *MockInboxStoreMockRecorder) DeleteSubscriptionsByAccounts(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionsByAccounts", reflect.TypeOf((*MockInboxStore)(nil).DeleteSubscriptionsByAccounts), ctx, roomID, accounts)
}

// DeleteThreadSubscriptions mocks base method.
func (m *MockInboxStore) DeleteThreadSubscriptions(ctx context.Context, roomID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteThreadSubscriptions", ctx, roomID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteThreadSubscriptions indicates an expected call of DeleteThreadSubscriptions.
func (mr *MockInboxStoreMockRecorder) DeleteThreadSubscriptions(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteThreadSubscriptions", reflect.TypeOf((*MockInboxStore)(nil).DeleteThreadSubscriptions), ctx, roomID, accounts)
}

// FindUsersByAccounts mocks base method.
func (m *MockInboxStore) FindUsersByAccounts(ctx context.Context, accounts []string) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByAccounts", ctx, accounts)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByAccounts indicates an expected call of FindUsersByAccounts.
func (mr *MockInboxStoreMockRecorder) FindUsersByAccounts(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByAccounts", reflect.TypeOf((*MockInboxStore)(nil).FindUsersByAccounts), ctx, accounts)
}

// HasRoomSubscription mocks base method.
func (m *MockInboxStore) HasRoomSubscription(ctx context.Context, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasRoomSubscription", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasRoomSubscription indicates an expected call of HasRoomSubscription.
func (mr *MockInboxStoreMockRecorder) HasRoomSubscription(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasRoomSubscription", reflect.TypeOf((*MockInboxStore)(nil).HasRoomSubscription), ctx, roomID)
}

// SetSubscriptionMentions mocks base method.
func (m *MockInboxStore) SetSubscriptionMentions(ctx context.Context, roomID string, accounts []string, msgCreatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscriptionMentions", ctx, roomID, accounts, msgCreatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscriptionMentions indicates an expected call of SetSubscriptionMentions.
func (mr *MockInboxStoreMockRecorder) SetSubscriptionMentions(ctx, roomID, accounts, msgCreatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscriptionMentions", reflect.TypeOf((*MockInboxStore)(nil).SetSubscriptionMentions), ctx, roomID, accounts, msgCreatedAt)
}

// UpdateSubscriptionFavorite mocks base method.
func (m *MockInboxStore) UpdateSubscriptionFavorite(ctx context.Context, roomID, account string, favorite bool, favoriteUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionFavorite", ctx, roomID, account, favorite, favoriteUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionFavorite indicates an expected call of UpdateSubscriptionFavorite.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionFavorite(ctx, roomID, account, favorite, favoriteUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionFavorite", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionFavorite), ctx, roomID, account, favorite, favoriteUpdatedAt)
}

// UpdateSubscriptionMute mocks base method.
func (m *MockInboxStore) UpdateSubscriptionMute(ctx context.Context, roomID, account string, muted bool, muteUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionMute", ctx, roomID, account, muted, muteUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionMute indicates an expected call of UpdateSubscriptionMute.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionMute(ctx, roomID, account, muted, muteUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionMute", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionMute), ctx, roomID, account, muted, muteUpdatedAt)
}

// UpdateSubscriptionNamesForRoom mocks base method.
func (m *MockInboxStore) UpdateSubscriptionNamesForRoom(ctx context.Context, roomID, newName string, nameUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionNamesForRoom", ctx, roomID, newName, nameUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionNamesForRoom indicates an expected call of UpdateSubscriptionNamesForRoom.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionNamesForRoom(ctx, roomID, newName, nameUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionNamesForRoom", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionNamesForRoom), ctx, roomID, newName, nameUpdatedAt)
}

// UpdateSubscriptionOpen mocks base method.
func (m *MockInboxStore) UpdateSubscriptionOpen(ctx context.Context, roomID, account string, open bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionOpen", ctx, roomID, account, open)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionOpen indicates an expected call of UpdateSubscriptionOpen.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionOpen(ctx, roomID, account, open any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionOpen", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionOpen), ctx, roomID, account, open)
}

// UpdateSubscriptionRead mocks base method.
func (m *MockInboxStore) UpdateSubscriptionRead(ctx context.Context, roomID, account string, lastSeenAt time.Time, alert bool) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionRead", ctx, roomID, account, lastSeenAt, alert)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateSubscriptionRead indicates an expected call of UpdateSubscriptionRead.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionRead(ctx, roomID, account, lastSeenAt, alert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionRead", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionRead), ctx, roomID, account, lastSeenAt, alert)
}

// UpdateSubscriptionRoles mocks base method.
func (m *MockInboxStore) UpdateSubscriptionRoles(ctx context.Context, account, roomID string, roles []model.Role, rolesUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionRoles", ctx, account, roomID, roles, rolesUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionRoles indicates an expected call of UpdateSubscriptionRoles.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionRoles(ctx, account, roomID, roles, rolesUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionRoles", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionRoles), ctx, account, roomID, roles, rolesUpdatedAt)
}

// UpdateSubscriptionSection mocks base method.
func (m *MockInboxStore) UpdateSubscriptionSection(ctx context.Context, roomID, account string, sectionID *string, order float64, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionSection", ctx, roomID, account, sectionID, order, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionSection indicates an expected call of UpdateSubscriptionSection.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionSection(ctx, roomID, account, sectionID, order, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionSection", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionSection), ctx, roomID, account, sectionID, order, updatedAt)
}

// UpdateUserChatlist mocks base method.
func (m *MockInboxStore) UpdateUserChatlist(ctx context.Context, account string, chatlist *model.ChatlistState, updatedAt int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserChatlist", ctx, account, chatlist, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserChatlist indicates an expected call of UpdateUserChatlist.
func (mr *MockInboxStoreMockRecorder) UpdateUserChatlist(ctx, account, chatlist, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserChatlist", reflect.TypeOf((*MockInboxStore)(nil).UpdateUserChatlist), ctx, account, chatlist, updatedAt)
}

// UpdateUserSettings mocks base method.
func (m *MockInboxStore) UpdateUserSettings(ctx context.Context, account string, settings *model.UserSettings, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserSettings", ctx, account, settings, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserSettings indicates an expected call of UpdateUserSettings.
func (mr *MockInboxStoreMockRecorder) UpdateUserSettings(ctx, account, settings, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserSettings", reflect.TypeOf((*MockInboxStore)(nil).UpdateUserSettings), ctx, account, settings, updatedAt)
}

// UpdateUserStatus mocks base method.
func (m *MockInboxStore) UpdateUserStatus(ctx context.Context, account, statusText string, statusIsShow *bool, statusUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserStatus", ctx, account, statusText, statusIsShow, statusUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserStatus indicates an expected call of UpdateUserStatus.
func (mr *MockInboxStoreMockRecorder) UpdateUserStatus(ctx, account, statusText, statusIsShow, statusUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserStatus", reflect.TypeOf((*MockInboxStore)(nil).UpdateUserStatus), ctx, account, statusText, statusIsShow, statusUpdatedAt)
}

// UpsertRemoteRoomActivity mocks base method.
func (m *MockInboxStore) UpsertRemoteRoomActivity(ctx context.Context, roomID, siteID string, lastMsgAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRemoteRoomActivity", ctx, roomID, siteID, lastMsgAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRemoteRoomActivity indicates an expected call of UpsertRemoteRoomActivity.
func (mr *MockInboxStoreMockRecorder) UpsertRemoteRoomActivity(ctx, roomID, siteID, lastMsgAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRemoteRoomActivity", reflect.TypeOf((*MockInboxStore)(nil).UpsertRemoteRoomActivity), ctx, roomID, siteID, lastMsgAt)
}

// UpsertRoom mocks base method.
func (m *MockInboxStore) UpsertRoom(ctx context.Context, room *model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRoom indicates an expected call of UpsertRoom.
func (mr *MockInboxStoreMockRecorder) UpsertRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRoom", reflect.TypeOf((*MockInboxStore)(nil).UpsertRoom), ctx, room)
}

// UpsertThreadSubscription mocks base method.
func (m *MockInboxStore) UpsertThreadSubscription(ctx context.Context, sub *model.ThreadSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertThreadSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertThreadSubscription indicates an expected call of UpsertThreadSubscription.
func (mr *MockInboxStoreMockRecorder) UpsertThreadSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertThreadSubscription", reflect.TypeOf((*MockInboxStore)(nil).UpsertThreadSubscription), ctx, sub)
}

// UpsertUserAccount mocks base method.
func (m *MockInboxStore) UpsertUserAccount(ctx context.Context, e *model.UserAccountUpdated, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserAccount", ctx, e, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserAccount indicates an expected call of UpsertUserAccount.
func (mr *MockInboxStoreMockRecorder) UpsertUserAccount(ctx, e, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserAccount", reflect.TypeOf((*MockInboxStore)(nil).UpsertUserAccount), ctx, e, updatedAt)
}
