// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/inbox-worker (interfaces: InboxStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . InboxStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockInboxStore is a mock of InboxStore interface.
type MockInboxStore struct {
	ctrl     *gomock.Controller
	recorder *MockInboxStoreMockRecorder
	isgomock struct{}
}

// MockInboxStoreMockRecorder is the mock recorder for MockInboxStore.
type MockInboxStoreMockRecorder struct {
	mock *MockInboxStore
}

// NewMockInboxStore creates a new mock instance.
func NewMockInboxStore(ctrl *gomock.Controller) *MockInboxStore {
	mock := &MockInboxStore{ctrl: ctrl}
	mock.recorder = &MockInboxStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInboxStore) EXPECT() *MockInboxStoreMockRecorder {
	return m.recorder
}

// ApplySubscriptionVisibility mocks base method.
func (m *MockInboxStore) ApplySubscriptionVisibility(ctx context.Context, roomID string, restricted, externalAccess bool, ownerAccount string, visibilityUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySubscriptionVisibility", ctx, roomID, restricted, externalAccess, ownerAccount, visibilityUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySubscriptionVisibility indicates an expected call of ApplySubscriptionVisibility.
func (mr *MockInboxStoreMockRecorder) ApplySubscriptionVisibility(ctx, roomID, restricted, externalAccess, ownerAccount, visibilityUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySubscriptionVisibility", reflect.TypeOf((*MockInboxStore)(nil).ApplySubscriptionVisibility), ctx, roomID, restricted, externalAccess, ownerAccount, visibilityUpdatedAt)
}

// ApplyThreadRead mocks base method.
func (m *MockInboxStore) ApplyThreadRead(ctx context.Context, roomID, threadRoomID, account string, newThreadUnread []string, alert bool, lastSeenAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyThreadRead", ctx, roomID, threadRoomID, account, newThreadUnread, alert, lastSeenAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyThreadRead indicates an expected call of ApplyThreadRead.
func (mr *MockInboxStoreMockRecorder) ApplyThreadRead(ctx, roomID, threadRoomID, account, newThreadUnread, alert, lastSeenAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyThreadRead", reflect.TypeOf((*MockInboxStore)(nil).ApplyThreadRead), ctx, roomID, threadRoomID, account, newThreadUnread, alert, lastSeenAt)
}

// BulkCreateSubscriptions mocks base method.
func (m *MockInboxStore) BulkCreateSubscriptions(ctx context.Context, subs []*model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateSubscriptions", ctx, subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreateSubscriptions indicates an expected call of BulkCreateSubscriptions.
func (mr *MockInboxStoreMockRecorder) BulkCreateSubscriptions(ctx, subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateSubscriptions", reflect.TypeOf((*MockInboxStore)(nil).BulkCreateSubscriptions), ctx, subs)
}

// CreateSubscription mocks base method.
func (m *MockInboxStore) CreateSubscription(ctx context.Context, sub *model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockInboxStoreMockRecorder) CreateSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockInboxStore)(nil).CreateSubscription), ctx, sub)
}

// DeleteSubscriptionsByAccounts mocks base method.
func (m *MockInboxStore) DeleteSubscriptionsByAccounts(ctx context.Context, roomID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionsByAccounts", ctx, roomID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubscriptionsByAccounts indicates an expected call of DeleteSubscriptionsByAccounts.
func (mr *MockInboxStoreMockRecorder) DeleteSubscriptionsByAccounts(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionsByAccounts", reflect.TypeOf((*MockInboxStore)(nil).DeleteSubscriptionsByAccounts), ctx, roomID, accounts)
}

// FindUsersByAccounts mocks base method.
func (m *MockInboxStore) FindUsersByAccounts(ctx context.Context, accounts []string) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByAccounts", ctx, accounts)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByAccounts indicates an expected call of FindUsersByAccounts.
func (mr *MockInboxStoreMockRecorder) FindUsersByAccounts(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByAccounts", reflect.TypeOf((*MockInboxStore)(nil).FindUsersByAccounts), ctx, accounts)
}

// UpdateSubscriptionFavorite mocks base method.
func (m *MockInboxStore) UpdateSubscriptionFavorite(ctx context.Context, roomID, account string, favorite bool, favoriteUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionFavorite", ctx, roomID, account, favorite, favoriteUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionFavorite indicates an expected call of UpdateSubscriptionFavorite.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionFavorite(ctx, roomID, account, favorite, favoriteUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionFavorite", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionFavorite), ctx, roomID, account, favorite, favoriteUpdatedAt)
}

// UpdateSubscriptionMute mocks base method.
func (m *MockInboxStore) UpdateSubscriptionMute(ctx context.Context, roomID, account string, muted bool, muteUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionMute", ctx, roomID, account, muted, muteUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionMute indicates an expected call of UpdateSubscriptionMute.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionMute(ctx, roomID, account, muted, muteUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionMute", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionMute), ctx, roomID, account, muted, muteUpdatedAt)
}

// UpdateSubscriptionNamesForRoom mocks base method.
func (m *MockInboxStore) UpdateSubscriptionNamesForRoom(ctx context.Context, roomID, newName string, nameUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionNamesForRoom", ctx, roomID, newName, nameUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionNamesForRoom indicates an expected call of UpdateSubscriptionNamesForRoom.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionNamesForRoom(ctx, roomID, newName, nameUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionNamesForRoom", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionNamesForRoom), ctx, roomID, newName, nameUpdatedAt)
}

// UpdateSubscriptionRead mocks base method.
func (m *MockInboxStore) UpdateSubscriptionRead(ctx context.Context, roomID, account string, lastSeenAt time.Time, alert bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionRead", ctx, roomID, account, lastSeenAt, alert)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionRead indicates an expected call of UpdateSubscriptionRead.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionRead(ctx, roomID, account, lastSeenAt, alert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionRead", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionRead), ctx, roomID, account, lastSeenAt, alert)
}

// UpdateSubscriptionRoles mocks base method.
func (m *MockInboxStore) UpdateSubscriptionRoles(ctx context.Context, account, roomID string, roles []model.Role, rolesUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionRoles", ctx, account, roomID, roles, rolesUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionRoles indicates an expected call of UpdateSubscriptionRoles.
func (mr *MockInboxStoreMockRecorder) UpdateSubscriptionRoles(ctx, account, roomID, roles, rolesUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionRoles", reflect.TypeOf((*MockInboxStore)(nil).UpdateSubscriptionRoles), ctx, account, roomID, roles, rolesUpdatedAt)
}

// UpsertRoom mocks base method.
func (m *MockInboxStore) UpsertRoom(ctx context.Context, room *model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertRoom indicates an expected call of UpsertRoom.
func (mr *MockInboxStoreMockRecorder) UpsertRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertRoom", reflect.TypeOf((*MockInboxStore)(nil).UpsertRoom), ctx, room)
}

// UpsertThreadSubscription mocks base method.
func (m *MockInboxStore) UpsertThreadSubscription(ctx context.Context, sub *model.ThreadSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertThreadSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertThreadSubscription indicates an expected call of UpsertThreadSubscription.
func (mr *MockInboxStoreMockRecorder) UpsertThreadSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertThreadSubscription", reflect.TypeOf((*MockInboxStore)(nil).UpsertThreadSubscription), ctx, sub)
}
