// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminStore is a mock of AdminStore interface.
type MockAdminStore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminStoreMockRecorder
	isgomock struct{}
}

// MockAdminStoreMockRecorder is the mock recorder for MockAdminStore.
type MockAdminStoreMockRecorder struct {
	mock *MockAdminStore
}

// NewMockAdminStore creates a new mock instance.
func NewMockAdminStore(ctrl *gomock.Controller) *MockAdminStore {
	mock := &MockAdminStore{ctrl: ctrl}
	mock.recorder = &MockAdminStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminStore) EXPECT() *MockAdminStoreMockRecorder {
	return m.recorder
}

// AppendAudit mocks base method.
func (m *MockAdminStore) AppendAudit(ctx context.Context, e *AuditEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendAudit", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendAudit indicates an expected call of AppendAudit.
func (mr *MockAdminStoreMockRecorder) AppendAudit(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAudit", reflect.TypeOf((*MockAdminStore)(nil).AppendAudit), ctx, e)
}

// CreateUser mocks base method.
func (m *MockAdminStore) CreateUser(ctx context.Context, u *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAdminStoreMockRecorder) CreateUser(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAdminStore)(nil).CreateUser), ctx, u)
}

// DeleteSession mocks base method.
func (m *MockAdminStore) DeleteSession(ctx context.Context, siteID, account, sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, siteID, account, sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockAdminStoreMockRecorder) DeleteSession(ctx, siteID, account, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockAdminStore)(nil).DeleteSession), ctx, siteID, account, sessionID)
}

// DeleteSessionsByAccount mocks base method.
func (m *MockAdminStore) DeleteSessionsByAccount(ctx context.Context, siteID, account string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSessionsByAccount", ctx, siteID, account)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSessionsByAccount indicates an expected call of DeleteSessionsByAccount.
func (mr *MockAdminStoreMockRecorder) DeleteSessionsByAccount(ctx, siteID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSessionsByAccount", reflect.TypeOf((*MockAdminStore)(nil).DeleteSessionsByAccount), ctx, siteID, account)
}

// EnsureIndexes mocks base method.
func (m *MockAdminStore) EnsureIndexes(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureIndexes", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureIndexes indicates an expected call of EnsureIndexes.
func (mr *MockAdminStoreMockRecorder) EnsureIndexes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureIndexes", reflect.TypeOf((*MockAdminStore)(nil).EnsureIndexes), ctx)
}

// FindSessionByHash mocks base method.
func (m *MockAdminStore) FindSessionByHash(ctx context.Context, hash string) (*Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSessionByHash", ctx, hash)
	ret0, _ := ret[0].(*Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSessionByHash indicates an expected call of FindSessionByHash.
func (mr *MockAdminStoreMockRecorder) FindSessionByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSessionByHash", reflect.TypeOf((*MockAdminStore)(nil).FindSessionByHash), ctx, hash)
}

// GetUserByAccount mocks base method.
func (m *MockAdminStore) GetUserByAccount(ctx context.Context, siteID, account string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByAccount", ctx, siteID, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByAccount indicates an expected call of GetUserByAccount.
func (mr *MockAdminStoreMockRecorder) GetUserByAccount(ctx, siteID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByAccount", reflect.TypeOf((*MockAdminStore)(nil).GetUserByAccount), ctx, siteID, account)
}

// ListAudit mocks base method.
func (m *MockAdminStore) ListAudit(ctx context.Context, siteID string, f AuditFilter, page, limit int) ([]AuditEntry, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAudit", ctx, siteID, f, page, limit)
	ret0, _ := ret[0].([]AuditEntry)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAudit indicates an expected call of ListAudit.
func (mr *MockAdminStoreMockRecorder) ListAudit(ctx, siteID, f, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAudit", reflect.TypeOf((*MockAdminStore)(nil).ListAudit), ctx, siteID, f, page, limit)
}

// ListSessionsByAccount mocks base method.
func (m *MockAdminStore) ListSessionsByAccount(ctx context.Context, siteID, account string) ([]Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSessionsByAccount", ctx, siteID, account)
	ret0, _ := ret[0].([]Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSessionsByAccount indicates an expected call of ListSessionsByAccount.
func (mr *MockAdminStoreMockRecorder) ListSessionsByAccount(ctx, siteID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSessionsByAccount", reflect.TypeOf((*MockAdminStore)(nil).ListSessionsByAccount), ctx, siteID, account)
}

// Ping mocks base method.
func (m *MockAdminStore) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAdminStoreMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAdminStore)(nil).Ping), ctx)
}

// SearchUsers mocks base method.
func (m *MockAdminStore) SearchUsers(ctx context.Context, siteID, q string, page, limit int) ([]model.User, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, siteID, q, page, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockAdminStoreMockRecorder) SearchUsers(ctx, siteID, q, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockAdminStore)(nil).SearchUsers), ctx, siteID, q, page, limit)
}

// UpdateUser mocks base method.
func (m *MockAdminStore) UpdateUser(ctx context.Context, siteID, account string, fields UserUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, siteID, account, fields)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockAdminStoreMockRecorder) UpdateUser(ctx, siteID, account, fields any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockAdminStore)(nil).UpdateUser), ctx, siteID, account, fields)
}

// UpdateUserPassword mocks base method.
func (m *MockAdminStore) UpdateUserPassword(ctx context.Context, siteID, account, bcryptHash string, requireChange bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPassword", ctx, siteID, account, bcryptHash, requireChange)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPassword indicates an expected call of UpdateUserPassword.
func (mr *MockAdminStoreMockRecorder) UpdateUserPassword(ctx, siteID, account, bcryptHash, requireChange any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPassword", reflect.TypeOf((*MockAdminStore)(nil).UpdateUserPassword), ctx, siteID, account, bcryptHash, requireChange)
}
