// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/tools/nats-debug (interfaces: Hub)
//
// Generated by this command:
//
//	mockgen -destination=mock_hub_test.go -package=main . Hub
//

// Package main is a generated GoMock package.
package main

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHub is a mock of Hub interface.
type MockHub struct {
	ctrl     *gomock.Controller
	recorder *MockHubMockRecorder
	isgomock struct{}
}

// MockHubMockRecorder is the mock recorder for MockHub.
type MockHubMockRecorder struct {
	mock *MockHub
}

// NewMockHub creates a new mock instance.
func NewMockHub(ctrl *gomock.Controller) *MockHub {
	mock := &MockHub{ctrl: ctrl}
	mock.recorder = &MockHubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHub) EXPECT() *MockHubMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockHub) Connect(sourceURL, destURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", sourceURL, destURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockHubMockRecorder) Connect(sourceURL, destURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockHub)(nil).Connect), sourceURL, destURL)
}

// ConnectRequest mocks base method.
func (m *MockHub) ConnectRequest(url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectRequest", url)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnectRequest indicates an expected call of ConnectRequest.
func (mr *MockHubMockRecorder) ConnectRequest(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectRequest", reflect.TypeOf((*MockHub)(nil).ConnectRequest), url)
}

// Disconnect mocks base method.
func (m *MockHub) Disconnect() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Disconnect")
}

// Disconnect indicates an expected call of Disconnect.
func (mr *MockHubMockRecorder) Disconnect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disconnect", reflect.TypeOf((*MockHub)(nil).Disconnect))
}

// DisconnectRequest mocks base method.
func (m *MockHub) DisconnectRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DisconnectRequest")
}

// DisconnectRequest indicates an expected call of DisconnectRequest.
func (mr *MockHubMockRecorder) DisconnectRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisconnectRequest", reflect.TypeOf((*MockHub)(nil).DisconnectRequest))
}

// Publish mocks base method.
func (m *MockHub) Publish(subject, payload string, dbg DebugHeaders) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", subject, payload, dbg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockHubMockRecorder) Publish(subject, payload, dbg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockHub)(nil).Publish), subject, payload, dbg)
}

// RegisterSSEClient mocks base method.
func (m *MockHub) RegisterSSEClient(ch chan<- Message) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterSSEClient", ch)
	ret0, _ := ret[0].(string)
	return ret0
}

// RegisterSSEClient indicates an expected call of RegisterSSEClient.
func (mr *MockHubMockRecorder) RegisterSSEClient(ch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterSSEClient", reflect.TypeOf((*MockHub)(nil).RegisterSSEClient), ch)
}

// Request mocks base method.
func (m *MockHub) Request(subject, payload string, timeoutMs int, dbg DebugHeaders) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", subject, payload, timeoutMs, dbg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockHubMockRecorder) Request(subject, payload, timeoutMs, dbg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockHub)(nil).Request), subject, payload, timeoutMs, dbg)
}

// Status mocks base method.
func (m *MockHub) Status() ConnectionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(ConnectionStatus)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockHubMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockHub)(nil).Status))
}

// Subscribe mocks base method.
func (m *MockHub) Subscribe(subject string) (Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", subject)
	ret0, _ := ret[0].(Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockHubMockRecorder) Subscribe(subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockHub)(nil).Subscribe), subject)
}

// Subscriptions mocks base method.
func (m *MockHub) Subscriptions() []Subscription {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscriptions")
	ret0, _ := ret[0].([]Subscription)
	return ret0
}

// Subscriptions indicates an expected call of Subscriptions.
func (mr *MockHubMockRecorder) Subscriptions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscriptions", reflect.TypeOf((*MockHub)(nil).Subscriptions))
}

// UnregisterSSEClient mocks base method.
func (m *MockHub) UnregisterSSEClient(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnregisterSSEClient", id)
}

// UnregisterSSEClient indicates an expected call of UnregisterSSEClient.
func (mr *MockHubMockRecorder) UnregisterSSEClient(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnregisterSSEClient", reflect.TypeOf((*MockHub)(nil).UnregisterSSEClient), id)
}

// Unsubscribe mocks base method.
func (m *MockHub) Unsubscribe(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockHubMockRecorder) Unsubscribe(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockHub)(nil).Unsubscribe), id)
}
