// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/message-worker (interfaces: Store,ThreadStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store,ThreadStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetMessageSender mocks base method.
func (m *MockStore) GetMessageSender(ctx context.Context, messageID string) (*cassParticipant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageSender", ctx, messageID)
	ret0, _ := ret[0].(*cassParticipant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageSender indicates an expected call of GetMessageSender.
func (mr *MockStoreMockRecorder) GetMessageSender(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageSender", reflect.TypeOf((*MockStore)(nil).GetMessageSender), ctx, messageID)
}

// SaveMessage mocks base method.
func (m *MockStore) SaveMessage(ctx context.Context, msg *model.Message, sender *cassParticipant, siteID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, msg, sender, siteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockStoreMockRecorder) SaveMessage(ctx, msg, sender, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockStore)(nil).SaveMessage), ctx, msg, sender, siteID)
}

// SaveThreadMessage mocks base method.
func (m *MockStore) SaveThreadMessage(ctx context.Context, msg *model.Message, sender *cassParticipant, siteID, threadRoomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveThreadMessage", ctx, msg, sender, siteID, threadRoomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveThreadMessage indicates an expected call of SaveThreadMessage.
func (mr *MockStoreMockRecorder) SaveThreadMessage(ctx, msg, sender, siteID, threadRoomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveThreadMessage", reflect.TypeOf((*MockStore)(nil).SaveThreadMessage), ctx, msg, sender, siteID, threadRoomID)
}

// UpdateParentMessageThreadRoomID mocks base method.
func (m *MockStore) UpdateParentMessageThreadRoomID(ctx context.Context, parentMessageID, roomID string, parentCreatedAt time.Time, threadRoomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParentMessageThreadRoomID", ctx, parentMessageID, roomID, parentCreatedAt, threadRoomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParentMessageThreadRoomID indicates an expected call of UpdateParentMessageThreadRoomID.
func (mr *MockStoreMockRecorder) UpdateParentMessageThreadRoomID(ctx, parentMessageID, roomID, parentCreatedAt, threadRoomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParentMessageThreadRoomID", reflect.TypeOf((*MockStore)(nil).UpdateParentMessageThreadRoomID), ctx, parentMessageID, roomID, parentCreatedAt, threadRoomID)
}

// MockThreadStore is a mock of ThreadStore interface.
type MockThreadStore struct {
	ctrl     *gomock.Controller
	recorder *MockThreadStoreMockRecorder
	isgomock struct{}
}

// MockThreadStoreMockRecorder is the mock recorder for MockThreadStore.
type MockThreadStoreMockRecorder struct {
	mock *MockThreadStore
}

// NewMockThreadStore creates a new mock instance.
func NewMockThreadStore(ctrl *gomock.Controller) *MockThreadStore {
	mock := &MockThreadStore{ctrl: ctrl}
	mock.recorder = &MockThreadStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadStore) EXPECT() *MockThreadStoreMockRecorder {
	return m.recorder
}

// CreateThreadRoom mocks base method.
func (m *MockThreadStore) CreateThreadRoom(ctx context.Context, room *model.ThreadRoom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThreadRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateThreadRoom indicates an expected call of CreateThreadRoom.
func (mr *MockThreadStoreMockRecorder) CreateThreadRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThreadRoom", reflect.TypeOf((*MockThreadStore)(nil).CreateThreadRoom), ctx, room)
}

// GetThreadRoomByParentMessageID mocks base method.
func (m *MockThreadStore) GetThreadRoomByParentMessageID(ctx context.Context, parentMessageID string) (*model.ThreadRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadRoomByParentMessageID", ctx, parentMessageID)
	ret0, _ := ret[0].(*model.ThreadRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadRoomByParentMessageID indicates an expected call of GetThreadRoomByParentMessageID.
func (mr *MockThreadStoreMockRecorder) GetThreadRoomByParentMessageID(ctx, parentMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadRoomByParentMessageID", reflect.TypeOf((*MockThreadStore)(nil).GetThreadRoomByParentMessageID), ctx, parentMessageID)
}

// InsertThreadSubscription mocks base method.
func (m *MockThreadStore) InsertThreadSubscription(ctx context.Context, sub *model.ThreadSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertThreadSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertThreadSubscription indicates an expected call of InsertThreadSubscription.
func (mr *MockThreadStoreMockRecorder) InsertThreadSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertThreadSubscription", reflect.TypeOf((*MockThreadStore)(nil).InsertThreadSubscription), ctx, sub)
}

// MarkThreadSubscriptionMention mocks base method.
func (m *MockThreadStore) MarkThreadSubscriptionMention(ctx context.Context, sub *model.ThreadSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkThreadSubscriptionMention", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkThreadSubscriptionMention indicates an expected call of MarkThreadSubscriptionMention.
func (mr *MockThreadStoreMockRecorder) MarkThreadSubscriptionMention(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkThreadSubscriptionMention", reflect.TypeOf((*MockThreadStore)(nil).MarkThreadSubscriptionMention), ctx, sub)
}

// UpdateThreadRoomLastMessage mocks base method.
func (m *MockThreadStore) UpdateThreadRoomLastMessage(ctx context.Context, threadRoomID, lastMsgID string, replyAccounts []string, lastMsgAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThreadRoomLastMessage", ctx, threadRoomID, lastMsgID, replyAccounts, lastMsgAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThreadRoomLastMessage indicates an expected call of UpdateThreadRoomLastMessage.
func (mr *MockThreadStoreMockRecorder) UpdateThreadRoomLastMessage(ctx, threadRoomID, lastMsgID, replyAccounts, lastMsgAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThreadRoomLastMessage", reflect.TypeOf((*MockThreadStore)(nil).UpdateThreadRoomLastMessage), ctx, threadRoomID, lastMsgID, replyAccounts, lastMsgAt)
}

// AddReplyAccounts mocks base method.
func (m *MockThreadStore) AddReplyAccounts(ctx context.Context, threadRoomID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReplyAccounts", ctx, threadRoomID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReplyAccounts indicates an expected call of AddReplyAccounts.
func (mr *MockThreadStoreMockRecorder) AddReplyAccounts(ctx, threadRoomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReplyAccounts", reflect.TypeOf((*MockThreadStore)(nil).AddReplyAccounts), ctx, threadRoomID, accounts)
}

// UpsertThreadSubscription mocks base method.
func (m *MockThreadStore) UpsertThreadSubscription(ctx context.Context, sub *model.ThreadSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertThreadSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertThreadSubscription indicates an expected call of UpsertThreadSubscription.
func (mr *MockThreadStoreMockRecorder) UpsertThreadSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertThreadSubscription", reflect.TypeOf((*MockThreadStore)(nil).UpsertThreadSubscription), ctx, sub)
}
