// Code generated by MockGen. DO NOT EDIT.
// Source: teamssender.go
//
// Generated by this command:
//
//	mockgen -source=teamssender.go -destination=mock_hridentity_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockHRIdentityStore is a mock of HRIdentityStore interface.
type MockHRIdentityStore struct {
	ctrl     *gomock.Controller
	recorder *MockHRIdentityStoreMockRecorder
	isgomock struct{}
}

// MockHRIdentityStoreMockRecorder is the mock recorder for MockHRIdentityStore.
type MockHRIdentityStoreMockRecorder struct {
	mock *MockHRIdentityStore
}

// NewMockHRIdentityStore creates a new mock instance.
func NewMockHRIdentityStore(ctrl *gomock.Controller) *MockHRIdentityStore {
	mock := &MockHRIdentityStore{ctrl: ctrl}
	mock.recorder = &MockHRIdentityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHRIdentityStore) EXPECT() *MockHRIdentityStoreMockRecorder {
	return m.recorder
}

// FindUserByDisplayName mocks base method.
func (m *MockHRIdentityStore) FindUserByDisplayName(ctx context.Context, name string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByDisplayName", ctx, name)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByDisplayName indicates an expected call of FindUserByDisplayName.
func (mr *MockHRIdentityStoreMockRecorder) FindUserByDisplayName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByDisplayName", reflect.TypeOf((*MockHRIdentityStore)(nil).FindUserByDisplayName), ctx, name)
}

// FindUserByEmployeeId mocks base method.
func (m *MockHRIdentityStore) FindUserByEmployeeId(ctx context.Context, employeeId string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmployeeId", ctx, employeeId)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmployeeId indicates an expected call of FindUserByEmployeeId.
func (mr *MockHRIdentityStoreMockRecorder) FindUserByEmployeeId(ctx, employeeId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmployeeId", reflect.TypeOf((*MockHRIdentityStore)(nil).FindUserByEmployeeId), ctx, employeeId)
}

// UpsertUserIdentities mocks base method.
func (m *MockHRIdentityStore) UpsertUserIdentities(ctx context.Context, users []model.IUserWithChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserIdentities", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserIdentities indicates an expected call of UpsertUserIdentities.
func (mr *MockHRIdentityStoreMockRecorder) UpsertUserIdentities(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserIdentities", reflect.TypeOf((*MockHRIdentityStore)(nil).UpsertUserIdentities), ctx, users)
}
