// Code generated by MockGen. DO NOT EDIT.
// Source: teamssender.go
//
// Generated by this command:
//
//	mockgen -source=teamssender.go -destination=mock_hridentity_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockidentityResolver is a mock of identityResolver interface.
type MockidentityResolver struct {
	ctrl     *gomock.Controller
	recorder *MockidentityResolverMockRecorder
	isgomock struct{}
}

// MockidentityResolverMockRecorder is the mock recorder for MockidentityResolver.
type MockidentityResolverMockRecorder struct {
	mock *MockidentityResolver
}

// NewMockidentityResolver creates a new mock instance.
func NewMockidentityResolver(ctrl *gomock.Controller) *MockidentityResolver {
	mock := &MockidentityResolver{ctrl: ctrl}
	mock.recorder = &MockidentityResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockidentityResolver) EXPECT() *MockidentityResolverMockRecorder {
	return m.recorder
}

// resolve mocks base method.
func (m *MockidentityResolver) resolve(ctx context.Context, teamsUserID, displayName string) (resolvedSender, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "resolve", ctx, teamsUserID, displayName)
	ret0, _ := ret[0].(resolvedSender)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// resolve indicates an expected call of resolve.
func (mr *MockidentityResolverMockRecorder) resolve(ctx, teamsUserID, displayName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "resolve", reflect.TypeOf((*MockidentityResolver)(nil).resolve), ctx, teamsUserID, displayName)
}

// MockHRIdentityStore is a mock of HRIdentityStore interface.
type MockHRIdentityStore struct {
	ctrl     *gomock.Controller
	recorder *MockHRIdentityStoreMockRecorder
	isgomock struct{}
}

// MockHRIdentityStoreMockRecorder is the mock recorder for MockHRIdentityStore.
type MockHRIdentityStoreMockRecorder struct {
	mock *MockHRIdentityStore
}

// NewMockHRIdentityStore creates a new mock instance.
func NewMockHRIdentityStore(ctrl *gomock.Controller) *MockHRIdentityStore {
	mock := &MockHRIdentityStore{ctrl: ctrl}
	mock.recorder = &MockHRIdentityStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHRIdentityStore) EXPECT() *MockHRIdentityStoreMockRecorder {
	return m.recorder
}

// AccountByTeamsID mocks base method.
func (m *MockHRIdentityStore) AccountByTeamsID(ctx context.Context, teamsUserID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountByTeamsID", ctx, teamsUserID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountByTeamsID indicates an expected call of AccountByTeamsID.
func (mr *MockHRIdentityStoreMockRecorder) AccountByTeamsID(ctx, teamsUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountByTeamsID", reflect.TypeOf((*MockHRIdentityStore)(nil).AccountByTeamsID), ctx, teamsUserID)
}

// FindUserByAccount mocks base method.
func (m *MockHRIdentityStore) FindUserByAccount(ctx context.Context, account string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByAccount", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByAccount indicates an expected call of FindUserByAccount.
func (mr *MockHRIdentityStoreMockRecorder) FindUserByAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByAccount", reflect.TypeOf((*MockHRIdentityStore)(nil).FindUserByAccount), ctx, account)
}

// UpsertUserIdentities mocks base method.
func (m *MockHRIdentityStore) UpsertUserIdentities(ctx context.Context, users []model.IUserWithChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserIdentities", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserIdentities indicates an expected call of UpsertUserIdentities.
func (mr *MockHRIdentityStoreMockRecorder) UpsertUserIdentities(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserIdentities", reflect.TypeOf((*MockHRIdentityStore)(nil).UpsertUserIdentities), ctx, users)
}
