// Code generated by MockGen. DO NOT EDIT.
// Source: memberlist_client.go
//
// Generated by this command:
//
//	mockgen -source=memberlist_client.go -destination=mock_memberlist_client_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMemberListClient is a mock of MemberListClient interface.
type MockMemberListClient struct {
	ctrl     *gomock.Controller
	recorder *MockMemberListClientMockRecorder
	isgomock struct{}
}

// MockMemberListClientMockRecorder is the mock recorder for MockMemberListClient.
type MockMemberListClientMockRecorder struct {
	mock *MockMemberListClient
}

// NewMockMemberListClient creates a new mock instance.
func NewMockMemberListClient(ctrl *gomock.Controller) *MockMemberListClient {
	mock := &MockMemberListClient{ctrl: ctrl}
	mock.recorder = &MockMemberListClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberListClient) EXPECT() *MockMemberListClientMockRecorder {
	return m.recorder
}

// ListMembers mocks base method.
func (m *MockMemberListClient) ListMembers(ctx context.Context, requester string, ch model.ChannelRef, limit int) ([]model.RoomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, requester, ch, limit)
	ret0, _ := ret[0].([]model.RoomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMemberListClientMockRecorder) ListMembers(ctx, requester, ch, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMemberListClient)(nil).ListMembers), ctx, requester, ch, limit)
}
