// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	roomkeystore "github.com/hmchangw/chat/pkg/roomkeystore"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomStore is a mock of RoomStore interface.
type MockRoomStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStoreMockRecorder
	isgomock struct{}
}

// MockRoomStoreMockRecorder is the mock recorder for MockRoomStore.
type MockRoomStoreMockRecorder struct {
	mock *MockRoomStore
}

// NewMockRoomStore creates a new mock instance.
func NewMockRoomStore(ctrl *gomock.Controller) *MockRoomStore {
	mock := &MockRoomStore{ctrl: ctrl}
	mock.recorder = &MockRoomStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStore) EXPECT() *MockRoomStoreMockRecorder {
	return m.recorder
}

// CountMembersAndOwners mocks base method.
func (m *MockRoomStore) CountMembersAndOwners(ctx context.Context, roomID string) (*RoomCounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountMembersAndOwners", ctx, roomID)
	ret0, _ := ret[0].(*RoomCounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountMembersAndOwners indicates an expected call of CountMembersAndOwners.
func (mr *MockRoomStoreMockRecorder) CountMembersAndOwners(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountMembersAndOwners", reflect.TypeOf((*MockRoomStore)(nil).CountMembersAndOwners), ctx, roomID)
}

// CountNewMembers mocks base method.
func (m *MockRoomStore) CountNewMembers(ctx context.Context, orgIDs, directAccounts []string, roomID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountNewMembers", ctx, orgIDs, directAccounts, roomID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountNewMembers indicates an expected call of CountNewMembers.
func (mr *MockRoomStoreMockRecorder) CountNewMembers(ctx, orgIDs, directAccounts, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountNewMembers", reflect.TypeOf((*MockRoomStore)(nil).CountNewMembers), ctx, orgIDs, directAccounts, roomID)
}

// CountOwners mocks base method.
func (m *MockRoomStore) CountOwners(ctx context.Context, roomID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOwners", ctx, roomID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOwners indicates an expected call of CountOwners.
func (mr *MockRoomStoreMockRecorder) CountOwners(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOwners", reflect.TypeOf((*MockRoomStore)(nil).CountOwners), ctx, roomID)
}

// CreateRoom mocks base method.
func (m *MockRoomStore) CreateRoom(ctx context.Context, room *model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomStoreMockRecorder) CreateRoom(ctx, room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoomStore)(nil).CreateRoom), ctx, room)
}

// CreateSubscription mocks base method.
func (m *MockRoomStore) CreateSubscription(ctx context.Context, sub *model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, sub)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockRoomStoreMockRecorder) CreateSubscription(ctx, sub any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockRoomStore)(nil).CreateSubscription), ctx, sub)
}

// GetRoom mocks base method.
func (m *MockRoomStore) GetRoom(ctx context.Context, id string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, id)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockRoomStoreMockRecorder) GetRoom(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockRoomStore)(nil).GetRoom), ctx, id)
}

// GetSubscription mocks base method.
func (m *MockRoomStore) GetSubscription(ctx context.Context, account, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, account, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockRoomStoreMockRecorder) GetSubscription(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockRoomStore)(nil).GetSubscription), ctx, account, roomID)
}

// GetSubscriptionWithMembership mocks base method.
func (m *MockRoomStore) GetSubscriptionWithMembership(ctx context.Context, roomID, account string) (*SubscriptionWithMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionWithMembership", ctx, roomID, account)
	ret0, _ := ret[0].(*SubscriptionWithMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionWithMembership indicates an expected call of GetSubscriptionWithMembership.
func (mr *MockRoomStoreMockRecorder) GetSubscriptionWithMembership(ctx, roomID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionWithMembership", reflect.TypeOf((*MockRoomStore)(nil).GetSubscriptionWithMembership), ctx, roomID, account)
}

// ListOrgMembers mocks base method.
func (m *MockRoomStore) ListOrgMembers(ctx context.Context, orgID string) ([]model.OrgMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrgMembers", ctx, orgID)
	ret0, _ := ret[0].([]model.OrgMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrgMembers indicates an expected call of ListOrgMembers.
func (mr *MockRoomStoreMockRecorder) ListOrgMembers(ctx, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrgMembers", reflect.TypeOf((*MockRoomStore)(nil).ListOrgMembers), ctx, orgID)
}

// ListRoomMembers mocks base method.
func (m *MockRoomStore) ListRoomMembers(ctx context.Context, roomID string, limit, offset *int, enrich bool) ([]model.RoomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomMembers", ctx, roomID, limit, offset, enrich)
	ret0, _ := ret[0].([]model.RoomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomMembers indicates an expected call of ListRoomMembers.
func (mr *MockRoomStoreMockRecorder) ListRoomMembers(ctx, roomID, limit, offset, enrich any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomMembers", reflect.TypeOf((*MockRoomStore)(nil).ListRoomMembers), ctx, roomID, limit, offset, enrich)
}

// ListRooms mocks base method.
func (m *MockRoomStore) ListRooms(ctx context.Context) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockRoomStoreMockRecorder) ListRooms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockRoomStore)(nil).ListRooms), ctx)
}

// ListRoomsByIDs mocks base method.
func (m *MockRoomStore) ListRoomsByIDs(ctx context.Context, ids []string) ([]model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoomsByIDs", ctx, ids)
	ret0, _ := ret[0].([]model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoomsByIDs indicates an expected call of ListRoomsByIDs.
func (mr *MockRoomStoreMockRecorder) ListRoomsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoomsByIDs", reflect.TypeOf((*MockRoomStore)(nil).ListRoomsByIDs), ctx, ids)
}

// MockRoomKeyStore is a mock of RoomKeyStore interface.
type MockRoomKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomKeyStoreMockRecorder
	isgomock struct{}
}

// MockRoomKeyStoreMockRecorder is the mock recorder for MockRoomKeyStore.
type MockRoomKeyStoreMockRecorder struct {
	mock *MockRoomKeyStore
}

// NewMockRoomKeyStore creates a new mock instance.
func NewMockRoomKeyStore(ctrl *gomock.Controller) *MockRoomKeyStore {
	mock := &MockRoomKeyStore{ctrl: ctrl}
	mock.recorder = &MockRoomKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomKeyStore) EXPECT() *MockRoomKeyStoreMockRecorder {
	return m.recorder
}

// GetMany mocks base method.
func (m *MockRoomKeyStore) GetMany(ctx context.Context, roomIDs []string) (map[string]*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMany", ctx, roomIDs)
	ret0, _ := ret[0].(map[string]*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockRoomKeyStoreMockRecorder) GetMany(ctx, roomIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockRoomKeyStore)(nil).GetMany), ctx, roomIDs)
}
