// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	msgraph "github.com/hmchangw/chat/pkg/msgraph"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsChatStore is a mock of TeamsChatStore interface.
type MockTeamsChatStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsChatStoreMockRecorder
	isgomock struct{}
}

// MockTeamsChatStoreMockRecorder is the mock recorder for MockTeamsChatStore.
type MockTeamsChatStoreMockRecorder struct {
	mock *MockTeamsChatStore
}

// NewMockTeamsChatStore creates a new mock instance.
func NewMockTeamsChatStore(ctrl *gomock.Controller) *MockTeamsChatStore {
	mock := &MockTeamsChatStore{ctrl: ctrl}
	mock.recorder = &MockTeamsChatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsChatStore) EXPECT() *MockTeamsChatStoreMockRecorder {
	return m.recorder
}

// ListChatsToSync mocks base method.
func (m *MockTeamsChatStore) ListChatsToSync(ctx context.Context) ([]ChatToSync, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatsToSync", ctx)
	ret0, _ := ret[0].([]ChatToSync)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatsToSync indicates an expected call of ListChatsToSync.
func (mr *MockTeamsChatStoreMockRecorder) ListChatsToSync(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatsToSync", reflect.TypeOf((*MockTeamsChatStore)(nil).ListChatsToSync), ctx)
}

// SetMembersSyncedBatch mocks base method.
func (m *MockTeamsChatStore) SetMembersSyncedBatch(ctx context.Context, updates []ChatMembersUpdate, now time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMembersSyncedBatch", ctx, updates, now)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMembersSyncedBatch indicates an expected call of SetMembersSyncedBatch.
func (mr *MockTeamsChatStoreMockRecorder) SetMembersSyncedBatch(ctx, updates, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMembersSyncedBatch", reflect.TypeOf((*MockTeamsChatStore)(nil).SetMembersSyncedBatch), ctx, updates, now)
}

// MockTeamsUserStore is a mock of TeamsUserStore interface.
type MockTeamsUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsUserStoreMockRecorder
	isgomock struct{}
}

// MockTeamsUserStoreMockRecorder is the mock recorder for MockTeamsUserStore.
type MockTeamsUserStoreMockRecorder struct {
	mock *MockTeamsUserStore
}

// NewMockTeamsUserStore creates a new mock instance.
func NewMockTeamsUserStore(ctrl *gomock.Controller) *MockTeamsUserStore {
	mock := &MockTeamsUserStore{ctrl: ctrl}
	mock.recorder = &MockTeamsUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsUserStore) EXPECT() *MockTeamsUserStoreMockRecorder {
	return m.recorder
}

// AccountsByIDs mocks base method.
func (m *MockTeamsUserStore) AccountsByIDs(ctx context.Context, ids []string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountsByIDs", ctx, ids)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountsByIDs indicates an expected call of AccountsByIDs.
func (mr *MockTeamsUserStoreMockRecorder) AccountsByIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountsByIDs", reflect.TypeOf((*MockTeamsUserStore)(nil).AccountsByIDs), ctx, ids)
}

// MockmembersFetcher is a mock of membersFetcher interface.
type MockmembersFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockmembersFetcherMockRecorder
	isgomock struct{}
}

// MockmembersFetcherMockRecorder is the mock recorder for MockmembersFetcher.
type MockmembersFetcherMockRecorder struct {
	mock *MockmembersFetcher
}

// NewMockmembersFetcher creates a new mock instance.
func NewMockmembersFetcher(ctrl *gomock.Controller) *MockmembersFetcher {
	mock := &MockmembersFetcher{ctrl: ctrl}
	mock.recorder = &MockmembersFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmembersFetcher) EXPECT() *MockmembersFetcherMockRecorder {
	return m.recorder
}

// ListChatMembers mocks base method.
func (m *MockmembersFetcher) ListChatMembers(ctx context.Context, chatID string) ([]msgraph.ChatMemberDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatMembers", ctx, chatID)
	ret0, _ := ret[0].([]msgraph.ChatMemberDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatMembers indicates an expected call of ListChatMembers.
func (mr *MockmembersFetcherMockRecorder) ListChatMembers(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatMembers", reflect.TypeOf((*MockmembersFetcher)(nil).ListChatMembers), ctx, chatID)
}
