// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	msgraph "github.com/hmchangw/chat/pkg/msgraph"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsUserStore is a mock of TeamsUserStore interface.
type MockTeamsUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsUserStoreMockRecorder
	isgomock struct{}
}

// MockTeamsUserStoreMockRecorder is the mock recorder for MockTeamsUserStore.
type MockTeamsUserStoreMockRecorder struct {
	mock *MockTeamsUserStore
}

// NewMockTeamsUserStore creates a new mock instance.
func NewMockTeamsUserStore(ctrl *gomock.Controller) *MockTeamsUserStore {
	mock := &MockTeamsUserStore{ctrl: ctrl}
	mock.recorder = &MockTeamsUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsUserStore) EXPECT() *MockTeamsUserStoreMockRecorder {
	return m.recorder
}

// ListUsers mocks base method.
func (m *MockTeamsUserStore) ListUsers(ctx context.Context) ([]model.TeamsUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx)
	ret0, _ := ret[0].([]model.TeamsUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockTeamsUserStoreMockRecorder) ListUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockTeamsUserStore)(nil).ListUsers), ctx)
}

// SetFrom mocks base method.
func (m *MockTeamsUserStore) SetFrom(ctx context.Context, userID string, from time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFrom", ctx, userID, from)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFrom indicates an expected call of SetFrom.
func (mr *MockTeamsUserStoreMockRecorder) SetFrom(ctx, userID, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFrom", reflect.TypeOf((*MockTeamsUserStore)(nil).SetFrom), ctx, userID, from)
}

// MockTeamsChatStore is a mock of TeamsChatStore interface.
type MockTeamsChatStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsChatStoreMockRecorder
	isgomock struct{}
}

// MockTeamsChatStoreMockRecorder is the mock recorder for MockTeamsChatStore.
type MockTeamsChatStoreMockRecorder struct {
	mock *MockTeamsChatStore
}

// NewMockTeamsChatStore creates a new mock instance.
func NewMockTeamsChatStore(ctrl *gomock.Controller) *MockTeamsChatStore {
	mock := &MockTeamsChatStore{ctrl: ctrl}
	mock.recorder = &MockTeamsChatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsChatStore) EXPECT() *MockTeamsChatStoreMockRecorder {
	return m.recorder
}

// UpsertChats mocks base method.
func (m *MockTeamsChatStore) UpsertChats(ctx context.Context, chats []model.TeamsChat, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertChats", ctx, chats, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertChats indicates an expected call of UpsertChats.
func (mr *MockTeamsChatStoreMockRecorder) UpsertChats(ctx, chats, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertChats", reflect.TypeOf((*MockTeamsChatStore)(nil).UpsertChats), ctx, chats, now)
}

// MockchatsFetcher is a mock of chatsFetcher interface.
type MockchatsFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockchatsFetcherMockRecorder
	isgomock struct{}
}

// MockchatsFetcherMockRecorder is the mock recorder for MockchatsFetcher.
type MockchatsFetcherMockRecorder struct {
	mock *MockchatsFetcher
}

// NewMockchatsFetcher creates a new mock instance.
func NewMockchatsFetcher(ctrl *gomock.Controller) *MockchatsFetcher {
	mock := &MockchatsFetcher{ctrl: ctrl}
	mock.recorder = &MockchatsFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatsFetcher) EXPECT() *MockchatsFetcherMockRecorder {
	return m.recorder
}

// ListUserChats mocks base method.
func (m *MockchatsFetcher) ListUserChats(ctx context.Context, userID string, from, to time.Time) ([]msgraph.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUserChats", ctx, userID, from, to)
	ret0, _ := ret[0].([]msgraph.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUserChats indicates an expected call of ListUserChats.
func (mr *MockchatsFetcherMockRecorder) ListUserChats(ctx, userID, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUserChats", reflect.TypeOf((*MockchatsFetcher)(nil).ListUserChats), ctx, userID, from, to)
}
