// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/notification-worker (interfaces: MemberStore,ThreadFollowerLister,UserSettingsSnapshotter)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . MemberStore,ThreadFollowerLister,UserSettingsSnapshotter
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	roomsubcache "github.com/hmchangw/chat/pkg/roomsubcache"
	gomock "go.uber.org/mock/gomock"
)

// MockMemberStore is a mock of MemberStore interface.
type MockMemberStore struct {
	ctrl     *gomock.Controller
	recorder *MockMemberStoreMockRecorder
	isgomock struct{}
}

// MockMemberStoreMockRecorder is the mock recorder for MockMemberStore.
type MockMemberStoreMockRecorder struct {
	mock *MockMemberStore
}

// NewMockMemberStore creates a new mock instance.
func NewMockMemberStore(ctrl *gomock.Controller) *MockMemberStore {
	mock := &MockMemberStore{ctrl: ctrl}
	mock.recorder = &MockMemberStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemberStore) EXPECT() *MockMemberStoreMockRecorder {
	return m.recorder
}

// ListMembers mocks base method.
func (m *MockMemberStore) ListMembers(ctx context.Context, roomID string) ([]roomsubcache.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, roomID)
	ret0, _ := ret[0].([]roomsubcache.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockMemberStoreMockRecorder) ListMembers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockMemberStore)(nil).ListMembers), ctx, roomID)
}

// MockThreadFollowerLister is a mock of ThreadFollowerLister interface.
type MockThreadFollowerLister struct {
	ctrl     *gomock.Controller
	recorder *MockThreadFollowerListerMockRecorder
	isgomock struct{}
}

// MockThreadFollowerListerMockRecorder is the mock recorder for MockThreadFollowerLister.
type MockThreadFollowerListerMockRecorder struct {
	mock *MockThreadFollowerLister
}

// NewMockThreadFollowerLister creates a new mock instance.
func NewMockThreadFollowerLister(ctrl *gomock.Controller) *MockThreadFollowerLister {
	mock := &MockThreadFollowerLister{ctrl: ctrl}
	mock.recorder = &MockThreadFollowerListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadFollowerLister) EXPECT() *MockThreadFollowerListerMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockThreadFollowerLister) Lookup(ctx context.Context, parentMessageID string) (ThreadRoomInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, parentMessageID)
	ret0, _ := ret[0].(ThreadRoomInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockThreadFollowerListerMockRecorder) Lookup(ctx, parentMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockThreadFollowerLister)(nil).Lookup), ctx, parentMessageID)
}

// MockUserSettingsSnapshotter is a mock of UserSettingsSnapshotter interface.
type MockUserSettingsSnapshotter struct {
	ctrl     *gomock.Controller
	recorder *MockUserSettingsSnapshotterMockRecorder
	isgomock struct{}
}

// MockUserSettingsSnapshotterMockRecorder is the mock recorder for MockUserSettingsSnapshotter.
type MockUserSettingsSnapshotterMockRecorder struct {
	mock *MockUserSettingsSnapshotter
}

// NewMockUserSettingsSnapshotter creates a new mock instance.
func NewMockUserSettingsSnapshotter(ctrl *gomock.Controller) *MockUserSettingsSnapshotter {
	mock := &MockUserSettingsSnapshotter{ctrl: ctrl}
	mock.recorder = &MockUserSettingsSnapshotterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSettingsSnapshotter) EXPECT() *MockUserSettingsSnapshotterMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockUserSettingsSnapshotter) Snapshot(ctx context.Context, accounts []string) (map[string]notifSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx, accounts)
	ret0, _ := ret[0].(map[string]notifSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockUserSettingsSnapshotterMockRecorder) Snapshot(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockUserSettingsSnapshotter)(nil).Snapshot), ctx, accounts)
}
