// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/search-sync-worker (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	searchengine "github.com/hmchangw/chat/pkg/searchengine"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Bulk mocks base method.
func (m *MockStore) Bulk(ctx context.Context, actions []searchengine.BulkAction) ([]searchengine.BulkResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bulk", ctx, actions)
	ret0, _ := ret[0].([]searchengine.BulkResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Bulk indicates an expected call of Bulk.
func (mr *MockStoreMockRecorder) Bulk(ctx, actions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bulk", reflect.TypeOf((*MockStore)(nil).Bulk), ctx, actions)
}

// UpdateByQuery mocks base method.
func (m *MockStore) UpdateByQuery(ctx context.Context, index string, body json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByQuery", ctx, index, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByQuery indicates an expected call of UpdateByQuery.
func (mr *MockStoreMockRecorder) UpdateByQuery(ctx, index, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByQuery", reflect.TypeOf((*MockStore)(nil).UpdateByQuery), ctx, index, body)
}
