// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/tools/loadgen (interfaces: soakLifecycleStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_soak_store_test.go -package=main . soakLifecycleStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MocksoakLifecycleStore is a mock of soakLifecycleStore interface.
type MocksoakLifecycleStore struct {
	ctrl     *gomock.Controller
	recorder *MocksoakLifecycleStoreMockRecorder
	isgomock struct{}
}

// MocksoakLifecycleStoreMockRecorder is the mock recorder for MocksoakLifecycleStore.
type MocksoakLifecycleStoreMockRecorder struct {
	mock *MocksoakLifecycleStore
}

// NewMocksoakLifecycleStore creates a new mock instance.
func NewMocksoakLifecycleStore(ctrl *gomock.Controller) *MocksoakLifecycleStore {
	mock := &MocksoakLifecycleStore{ctrl: ctrl}
	mock.recorder = &MocksoakLifecycleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksoakLifecycleStore) EXPECT() *MocksoakLifecycleStoreMockRecorder {
	return m.recorder
}

// GetManifest mocks base method.
func (m *MocksoakLifecycleStore) GetManifest(arg0 context.Context, arg1 string) (*soakManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManifest", arg0, arg1)
	ret0, _ := ret[0].(*soakManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManifest indicates an expected call of GetManifest.
func (mr *MocksoakLifecycleStoreMockRecorder) GetManifest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManifest", reflect.TypeOf((*MocksoakLifecycleStore)(nil).GetManifest), arg0, arg1)
}

// PutManifest mocks base method.
func (m *MocksoakLifecycleStore) PutManifest(arg0 context.Context, arg1 *soakManifest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutManifest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutManifest indicates an expected call of PutManifest.
func (mr *MocksoakLifecycleStoreMockRecorder) PutManifest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutManifest", reflect.TypeOf((*MocksoakLifecycleStore)(nil).PutManifest), arg0, arg1)
}

// TouchHeartbeat mocks base method.
func (m *MocksoakLifecycleStore) TouchHeartbeat(arg0 context.Context, arg1 string, arg2 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchHeartbeat", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchHeartbeat indicates an expected call of TouchHeartbeat.
func (mr *MocksoakLifecycleStoreMockRecorder) TouchHeartbeat(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchHeartbeat", reflect.TypeOf((*MocksoakLifecycleStore)(nil).TouchHeartbeat), arg0, arg1, arg2)
}
