// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/tools/loadgen (interfaces: soakSeedStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_soak_store_test.go -package=main . soakSeedStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MocksoakSeedStore is a mock of soakSeedStore interface.
type MocksoakSeedStore struct {
	ctrl     *gomock.Controller
	recorder *MocksoakSeedStoreMockRecorder
	isgomock struct{}
}

// MocksoakSeedStoreMockRecorder is the mock recorder for MocksoakSeedStore.
type MocksoakSeedStoreMockRecorder struct {
	mock *MocksoakSeedStore
}

// NewMocksoakSeedStore creates a new mock instance.
func NewMocksoakSeedStore(ctrl *gomock.Controller) *MocksoakSeedStore {
	mock := &MocksoakSeedStore{ctrl: ctrl}
	mock.recorder = &MocksoakSeedStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksoakSeedStore) EXPECT() *MocksoakSeedStoreMockRecorder {
	return m.recorder
}

// BorrowUsers mocks base method.
func (m *MocksoakSeedStore) BorrowUsers(ctx context.Context, siteID string, limit int) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BorrowUsers", ctx, siteID, limit)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BorrowUsers indicates an expected call of BorrowUsers.
func (mr *MocksoakSeedStoreMockRecorder) BorrowUsers(ctx, siteID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BorrowUsers", reflect.TypeOf((*MocksoakSeedStore)(nil).BorrowUsers), ctx, siteID, limit)
}

// InsertOwnedRooms mocks base method.
func (m *MocksoakSeedStore) InsertOwnedRooms(ctx context.Context, runID string, rooms []model.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOwnedRooms", ctx, runID, rooms)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOwnedRooms indicates an expected call of InsertOwnedRooms.
func (mr *MocksoakSeedStoreMockRecorder) InsertOwnedRooms(ctx, runID, rooms any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOwnedRooms", reflect.TypeOf((*MocksoakSeedStore)(nil).InsertOwnedRooms), ctx, runID, rooms)
}

// InsertOwnedSubscriptions mocks base method.
func (m *MocksoakSeedStore) InsertOwnedSubscriptions(ctx context.Context, runID string, subscriptions []model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOwnedSubscriptions", ctx, runID, subscriptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOwnedSubscriptions indicates an expected call of InsertOwnedSubscriptions.
func (mr *MocksoakSeedStoreMockRecorder) InsertOwnedSubscriptions(ctx, runID, subscriptions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOwnedSubscriptions", reflect.TypeOf((*MocksoakSeedStore)(nil).InsertOwnedSubscriptions), ctx, runID, subscriptions)
}

// PutManifest mocks base method.
func (m *MocksoakSeedStore) PutManifest(ctx context.Context, manifest *soakManifest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutManifest", ctx, manifest)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutManifest indicates an expected call of PutManifest.
func (mr *MocksoakSeedStoreMockRecorder) PutManifest(ctx, manifest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutManifest", reflect.TypeOf((*MocksoakSeedStore)(nil).PutManifest), ctx, manifest)
}

// ReplaceOwnershipChunks mocks base method.
func (m *MocksoakSeedStore) ReplaceOwnershipChunks(ctx context.Context, runID string, chunks [][]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceOwnershipChunks", ctx, runID, chunks)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceOwnershipChunks indicates an expected call of ReplaceOwnershipChunks.
func (mr *MocksoakSeedStoreMockRecorder) ReplaceOwnershipChunks(ctx, runID, chunks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceOwnershipChunks", reflect.TypeOf((*MocksoakSeedStore)(nil).ReplaceOwnershipChunks), ctx, runID, chunks)
}

// ResetOwned mocks base method.
func (m *MocksoakSeedStore) ResetOwned(ctx context.Context, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetOwned", ctx, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetOwned indicates an expected call of ResetOwned.
func (mr *MocksoakSeedStoreMockRecorder) ResetOwned(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetOwned", reflect.TypeOf((*MocksoakSeedStore)(nil).ResetOwned), ctx, runID)
}
