// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockavatarStore is a mock of avatarStore interface.
type MockavatarStore struct {
	ctrl     *gomock.Controller
	recorder *MockavatarStoreMockRecorder
	isgomock struct{}
}

// MockavatarStoreMockRecorder is the mock recorder for MockavatarStore.
type MockavatarStoreMockRecorder struct {
	mock *MockavatarStore
}

// NewMockavatarStore creates a new mock instance.
func NewMockavatarStore(ctrl *gomock.Controller) *MockavatarStore {
	mock := &MockavatarStore{ctrl: ctrl}
	mock.recorder = &MockavatarStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockavatarStore) EXPECT() *MockavatarStoreMockRecorder {
	return m.recorder
}

// Avatar mocks base method.
func (m *MockavatarStore) Avatar(ctx context.Context, subjectType model.AvatarSubjectType, subjectID string) (*model.Avatar, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Avatar", ctx, subjectType, subjectID)
	ret0, _ := ret[0].(*model.Avatar)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Avatar indicates an expected call of Avatar.
func (mr *MockavatarStoreMockRecorder) Avatar(ctx, subjectType, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Avatar", reflect.TypeOf((*MockavatarStore)(nil).Avatar), ctx, subjectType, subjectID)
}

// BotSite mocks base method.
func (m *MockavatarStore) BotSite(ctx context.Context, account string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotSite", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// BotSite indicates an expected call of BotSite.
func (mr *MockavatarStoreMockRecorder) BotSite(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotSite", reflect.TypeOf((*MockavatarStore)(nil).BotSite), ctx, account)
}

// EmployeeID mocks base method.
func (m *MockavatarStore) EmployeeID(ctx context.Context, account string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmployeeID", ctx, account)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EmployeeID indicates an expected call of EmployeeID.
func (mr *MockavatarStoreMockRecorder) EmployeeID(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmployeeID", reflect.TypeOf((*MockavatarStore)(nil).EmployeeID), ctx, account)
}

// RoomMember mocks base method.
func (m *MockavatarStore) RoomMember(ctx context.Context, roomID, account string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomMember", ctx, roomID, account)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomMember indicates an expected call of RoomMember.
func (mr *MockavatarStoreMockRecorder) RoomMember(ctx, roomID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomMember", reflect.TypeOf((*MockavatarStore)(nil).RoomMember), ctx, roomID, account)
}

// RoomSite mocks base method.
func (m *MockavatarStore) RoomSite(ctx context.Context, roomID string) (string, model.RoomType, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomSite", ctx, roomID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(model.RoomType)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(bool)
	ret4, _ := ret[4].(error)
	return ret0, ret1, ret2, ret3, ret4
}

// RoomSite indicates an expected call of RoomSite.
func (mr *MockavatarStoreMockRecorder) RoomSite(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomSite", reflect.TypeOf((*MockavatarStore)(nil).RoomSite), ctx, roomID)
}

// SetBotAvatar mocks base method.
func (m *MockavatarStore) SetBotAvatar(ctx context.Context, av *model.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBotAvatar", ctx, av)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBotAvatar indicates an expected call of SetBotAvatar.
func (mr *MockavatarStoreMockRecorder) SetBotAvatar(ctx, av any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotAvatar", reflect.TypeOf((*MockavatarStore)(nil).SetBotAvatar), ctx, av)
}

// UserByAccount mocks base method.
func (m *MockavatarStore) UserByAccount(ctx context.Context, account string) (*model.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserByAccount", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UserByAccount indicates an expected call of UserByAccount.
func (mr *MockavatarStoreMockRecorder) UserByAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserByAccount", reflect.TypeOf((*MockavatarStore)(nil).UserByAccount), ctx, account)
}

// MockemojiStore is a mock of emojiStore interface.
type MockemojiStore struct {
	ctrl     *gomock.Controller
	recorder *MockemojiStoreMockRecorder
	isgomock struct{}
}

// MockemojiStoreMockRecorder is the mock recorder for MockemojiStore.
type MockemojiStoreMockRecorder struct {
	mock *MockemojiStore
}

// NewMockemojiStore creates a new mock instance.
func NewMockemojiStore(ctrl *gomock.Controller) *MockemojiStore {
	mock := &MockemojiStore{ctrl: ctrl}
	mock.recorder = &MockemojiStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockemojiStore) EXPECT() *MockemojiStoreMockRecorder {
	return m.recorder
}

// DeleteEmoji mocks base method.
func (m *MockemojiStore) DeleteEmoji(ctx context.Context, siteID, shortcode string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEmoji", ctx, siteID, shortcode)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteEmoji indicates an expected call of DeleteEmoji.
func (mr *MockemojiStoreMockRecorder) DeleteEmoji(ctx, siteID, shortcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEmoji", reflect.TypeOf((*MockemojiStore)(nil).DeleteEmoji), ctx, siteID, shortcode)
}

// EmojiDoc mocks base method.
func (m *MockemojiStore) EmojiDoc(ctx context.Context, siteID, shortcode string) (*model.CustomEmoji, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmojiDoc", ctx, siteID, shortcode)
	ret0, _ := ret[0].(*model.CustomEmoji)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EmojiDoc indicates an expected call of EmojiDoc.
func (mr *MockemojiStoreMockRecorder) EmojiDoc(ctx, siteID, shortcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmojiDoc", reflect.TypeOf((*MockemojiStore)(nil).EmojiDoc), ctx, siteID, shortcode)
}

// ListEmojis mocks base method.
func (m *MockemojiStore) ListEmojis(ctx context.Context, siteID string) ([]model.CustomEmoji, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmojis", ctx, siteID)
	ret0, _ := ret[0].([]model.CustomEmoji)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmojis indicates an expected call of ListEmojis.
func (mr *MockemojiStoreMockRecorder) ListEmojis(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmojis", reflect.TypeOf((*MockemojiStore)(nil).ListEmojis), ctx, siteID)
}

// UpsertEmoji mocks base method.
func (m *MockemojiStore) UpsertEmoji(ctx context.Context, e *model.CustomEmoji) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEmoji", ctx, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEmoji indicates an expected call of UpsertEmoji.
func (mr *MockemojiStoreMockRecorder) UpsertEmoji(ctx, e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEmoji", reflect.TypeOf((*MockemojiStore)(nil).UpsertEmoji), ctx, e)
}
