// Code generated by MockGen. DO NOT EDIT.
// Source: publisher.go
//
// Generated by this command:
//
//	mockgen -source=publisher.go -destination=mock_publisher_test.go -package=publisher
//

// Package publisher is a generated GoMock package.
package publisher

import (
	context "context"
	reflect "reflect"

	natsmetrics "github.com/hmchangw/chat/pkg/natsmetrics"
	gomock "go.uber.org/mock/gomock"
)

// MockattemptRecorder is a mock of attemptRecorder interface.
type MockattemptRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockattemptRecorderMockRecorder
	isgomock struct{}
}

// MockattemptRecorderMockRecorder is the mock recorder for MockattemptRecorder.
type MockattemptRecorderMockRecorder struct {
	mock *MockattemptRecorder
}

// NewMockattemptRecorder creates a new mock instance.
func NewMockattemptRecorder(ctrl *gomock.Controller) *MockattemptRecorder {
	mock := &MockattemptRecorder{ctrl: ctrl}
	mock.recorder = &MockattemptRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockattemptRecorder) EXPECT() *MockattemptRecorderMockRecorder {
	return m.recorder
}

// Attempt mocks base method.
func (m *MockattemptRecorder) Attempt(arg0 context.Context, arg1 natsmetrics.DestinationKind, arg2 natsmetrics.Operation, arg3 error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Attempt", arg0, arg1, arg2, arg3)
}

// Attempt indicates an expected call of Attempt.
func (mr *MockattemptRecorderMockRecorder) Attempt(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attempt", reflect.TypeOf((*MockattemptRecorder)(nil).Attempt), arg0, arg1, arg2, arg3)
}
