// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/room-state-worker (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// BulkAdvanceLastSeen mocks base method.
func (m *MockStore) BulkAdvanceLastSeen(ctx context.Context, updates map[subKey]time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkAdvanceLastSeen", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkAdvanceLastSeen indicates an expected call of BulkAdvanceLastSeen.
func (mr *MockStoreMockRecorder) BulkAdvanceLastSeen(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkAdvanceLastSeen", reflect.TypeOf((*MockStore)(nil).BulkAdvanceLastSeen), ctx, updates)
}

// BulkSetMentions mocks base method.
func (m *MockStore) BulkSetMentions(ctx context.Context, updates map[subKey]time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkSetMentions", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkSetMentions indicates an expected call of BulkSetMentions.
func (mr *MockStoreMockRecorder) BulkSetMentions(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkSetMentions", reflect.TypeOf((*MockStore)(nil).BulkSetMentions), ctx, updates)
}

// BulkUpdateRoomLastMessage mocks base method.
func (m *MockStore) BulkUpdateRoomLastMessage(ctx context.Context, updates map[string]roomLastMsgUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpdateRoomLastMessage", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpdateRoomLastMessage indicates an expected call of BulkUpdateRoomLastMessage.
func (mr *MockStoreMockRecorder) BulkUpdateRoomLastMessage(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpdateRoomLastMessage", reflect.TypeOf((*MockStore)(nil).BulkUpdateRoomLastMessage), ctx, updates)
}
