apiVersion: v1
kind: Service
metadata:
  name: {{ include "cassandra-soak.fullname" . }}-metrics
  labels:
    {{- include "cassandra-soak.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.metrics.serviceAnnotations | nindent 4 }}
spec:
  selector:
    {{- include "cassandra-soak.selectorLabels" . | nindent 4 }}
    loadgen.newchat/phase: soak
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
