// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/data-migration/oplog-connector (interfaces: CheckpointStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . CheckpointStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCheckpointStore is a mock of CheckpointStore interface.
type MockCheckpointStore struct {
	ctrl     *gomock.Controller
	recorder *MockCheckpointStoreMockRecorder
	isgomock struct{}
}

// MockCheckpointStoreMockRecorder is the mock recorder for MockCheckpointStore.
type MockCheckpointStoreMockRecorder struct {
	mock *MockCheckpointStore
}

// NewMockCheckpointStore creates a new mock instance.
func NewMockCheckpointStore(ctrl *gomock.Controller) *MockCheckpointStore {
	mock := &MockCheckpointStore{ctrl: ctrl}
	mock.recorder = &MockCheckpointStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckpointStore) EXPECT() *MockCheckpointStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockCheckpointStore) Load(ctx context.Context, collection string) (*Checkpoint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, collection)
	ret0, _ := ret[0].(*Checkpoint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockCheckpointStoreMockRecorder) Load(ctx, collection any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockCheckpointStore)(nil).Load), ctx, collection)
}

// Save mocks base method.
func (m *MockCheckpointStore) Save(ctx context.Context, cp *Checkpoint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, cp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCheckpointStoreMockRecorder) Save(ctx, cp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCheckpointStore)(nil).Save), ctx, cp)
}
