// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCardStore is a mock of CardStore interface.
type MockCardStore struct {
	ctrl     *gomock.Controller
	recorder *MockCardStoreMockRecorder
	isgomock struct{}
}

// MockCardStoreMockRecorder is the mock recorder for MockCardStore.
type MockCardStoreMockRecorder struct {
	mock *MockCardStore
}

// NewMockCardStore creates a new mock instance.
func NewMockCardStore(ctrl *gomock.Controller) *MockCardStore {
	mock := &MockCardStore{ctrl: ctrl}
	mock.recorder = &MockCardStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCardStore) EXPECT() *MockCardStoreMockRecorder {
	return m.recorder
}

// ListCards mocks base method.
func (m *MockCardStore) ListCards(ctx context.Context) ([]card, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCards", ctx)
	ret0, _ := ret[0].([]card)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCards indicates an expected call of ListCards.
func (mr *MockCardStoreMockRecorder) ListCards(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCards", reflect.TypeOf((*MockCardStore)(nil).ListCards), ctx)
}
