// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ExistingIDs mocks base method.
func (m *MockStore) ExistingIDs(ctx context.Context, ids []string) (map[string]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistingIDs", ctx, ids)
	ret0, _ := ret[0].(map[string]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistingIDs indicates an expected call of ExistingIDs.
func (mr *MockStoreMockRecorder) ExistingIDs(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistingIDs", reflect.TypeOf((*MockStore)(nil).ExistingIDs), ctx, ids)
}

// HRUsers mocks base method.
func (m *MockStore) HRUsers(ctx context.Context, accounts []string) (map[string]hrUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HRUsers", ctx, accounts)
	ret0, _ := ret[0].(map[string]hrUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HRUsers indicates an expected call of HRUsers.
func (mr *MockStoreMockRecorder) HRUsers(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HRUsers", reflect.TypeOf((*MockStore)(nil).HRUsers), ctx, accounts)
}

// UpsertTeamsUsers mocks base method.
func (m *MockStore) UpsertTeamsUsers(ctx context.Context, users []model.TeamsUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTeamsUsers", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTeamsUsers indicates an expected call of UpsertTeamsUsers.
func (mr *MockStoreMockRecorder) UpsertTeamsUsers(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTeamsUsers", reflect.TypeOf((*MockStore)(nil).UpsertTeamsUsers), ctx, users)
}
