#!/usr/bin/env bash
#
# Generates NATS operator + account keys and writes nats.conf, backend.creds,
# and .env for the shared local-dev NATS instance.
#
# Uses the nats-box Docker image so it works on any OS (Mac, Ubuntu, etc.)
# without requiring local nsc/nk installation.
#
# Run once before `make deps-up`.
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
NATS_CONF="$SCRIPT_DIR/nats.conf"
BACKEND_CREDS="$SCRIPT_DIR/backend.creds"
FRONTEND_ENV_FILE="$REPO_ROOT/chat-frontend/.env.local"
NATS_BOX_IMAGE="natsio/nats-box:latest"

echo "=== docker-local — Shared NATS Setup ==="
echo ""

if ! command -v docker &>/dev/null; then
  echo "ERROR: docker not found. Install Docker first."
  exit 1
fi

echo "Generating NATS operator + account keys via nats-box..."
echo ""

if [ -n "${NATS_SETUP_TMP_ROOT:-}" ]; then
  mkdir -p "$NATS_SETUP_TMP_ROOT"
  SETUP_TMP_DIR=$(mktemp -d "$NATS_SETUP_TMP_ROOT/nats-setup.XXXXXX")
else
  SETUP_TMP_DIR=$(mktemp -d)
fi
trap 'rm -rf "$SETUP_TMP_DIR"' EXIT

docker run --rm \
  -v "$SETUP_TMP_DIR:/output" \
  "$NATS_BOX_IMAGE" \
  sh -c '
    set -e

    nsc add operator --name localdev --sys 2>&1 | sed "s/^/  /"
    nsc env -o localdev >/dev/null 2>&1

    nsc add account --name chatapp 2>&1 | sed "s/^/  /"
    nsc edit account chatapp --js-mem-storage 512M --js-disk-storage 5G --js-streams 10 2>&1 | sed "s/^/  /"

    # Scoped signing key that auth-service uses to sign user JWTs. The role
    # template mirrors the grants auth-service used to inline per JWT, keyed
    # off the account:<account> tag every user JWT now carries.
    nsc edit signing-key --account chatapp --sk generate --role scoped_user \
      --allow-sub "chat.user.{{tag(account)}}.>" \
      --allow-sub "chat.room.>" \
      --allow-sub "chat.local.room.>" \
      --allow-sub "_INBOX.>" \
      --allow-sub "chat.user.presence.state.*" \
      --allow-pub "chat.user.{{tag(account)}}.>" \
      --allow-pub "_INBOX.>" \
      --allow-pub "chat.user.presence.*.query.batch" \
      --allow-pub-response \
      > /output/sk_edit.log 2>&1
    AUTH_SK_PUB=$(grep -Eo "A[A-Z0-9]{55}" /output/sk_edit.log | head -1)
    if [ -z "$AUTH_SK_PUB" ]; then
      echo "ERROR: failed to extract auth-service signing key pubkey"
      cat /output/sk_edit.log
      exit 1
    fi

    nsc describe operator --raw > /output/operator.jwt
    nsc describe account chatapp --raw > /output/account.jwt
    nsc describe account SYS --raw > /output/sys.jwt

    nsc describe account chatapp 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/account_pub.txt
    nsc describe account SYS 2>/dev/null | grep "Account ID" | awk -F"|" "{gsub(/[ \t]/, \"\", \$3); print \$3}" > /output/sys_pub.txt

    AUTH_SK_SEED_FILE=$(find /root/.local/share/nats/nsc/keys -name "${AUTH_SK_PUB}.nk" 2>/dev/null | head -1)
    if [ -z "$AUTH_SK_SEED_FILE" ]; then
      AUTH_SK_SEED_FILE=$(find /nsc -name "${AUTH_SK_PUB}.nk" 2>/dev/null | head -1)
    fi
    if [ -z "$AUTH_SK_SEED_FILE" ]; then
      echo "ERROR: Could not find seed for signing key ${AUTH_SK_PUB}"
      exit 1
    fi
    cat "$AUTH_SK_SEED_FILE" > /output/auth_sk_seed.txt

    nsc add user --account chatapp --name backend
    nsc edit user --account chatapp --name backend --allow-sub ">" --allow-pub ">"
    nsc generate creds --account chatapp --name backend > /output/backend.creds
  '

cp "$SETUP_TMP_DIR/backend.creds" "$BACKEND_CREDS"
# 0644, not 0600: service containers run as non-root (uid 10001) and
# bind-mount this file read-only at /etc/nats/backend.creds, so the
# in-container user must be able to read it. Acceptable only because
# this is a throwaway local-dev credential generated by this script.
chmod 644 "$BACKEND_CREDS"

OPERATOR_JWT=$(cat "$SETUP_TMP_DIR/operator.jwt")
ACCOUNT_JWT=$(cat "$SETUP_TMP_DIR/account.jwt")
SYS_JWT=$(cat "$SETUP_TMP_DIR/sys.jwt")
ACCOUNT_PUB_KEY=$(cat "$SETUP_TMP_DIR/account_pub.txt")
SYS_PUB_KEY=$(cat "$SETUP_TMP_DIR/sys_pub.txt")
AUTH_SK_SEED=$(cat "$SETUP_TMP_DIR/auth_sk_seed.txt")

echo ""
echo "  Operator JWT:       ${OPERATOR_JWT:0:50}..."
echo "  Account Public Key: $ACCOUNT_PUB_KEY"
echo "  Auth SK Seed:       <hidden — written to $ENV_FILE>"
echo "  SYS Public Key:     $SYS_PUB_KEY"
echo "  Backend creds:      $BACKEND_CREDS"
echo ""

cat > "$ENV_FILE" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

# Auth-service signs user JWTs with the chatapp account's scoped signing key.
# The scope template supplies per-user permissions; auth-service stamps the
# account tag on each JWT so {{tag(account)}} resolves to the right subjects.
# The account pubkey goes on the JWT as issuer_account so the NATS resolver
# can attribute the SK back to the account.
# All other microservices authenticate with backend.creds via NATS_CREDS_FILE.
AUTH_SCOPED_SIGNING_KEY=${AUTH_SK_SEED}
AUTH_ACCOUNT_PUB_KEY=${ACCOUNT_PUB_KEY}

# Shared NATS endpoint inside the chat-local docker network.
NATS_URL=nats://nats:4222
NATS_CREDS_FILE=/etc/nats/backend.creds

# Bypass OIDC; flip to false stack-wide (auth, portal, upload, botplatform,
# chat-frontend all read this) to test the OIDC flow.
DEV_MODE=true

# Every setting in the service compose files is overridable from here — grep a
# compose file for \${ to see a service's own knobs. The common ones:
#
# Published host ports (change one to dodge a conflict; the URLs follow).
#GATEWAY_HOST_PORT=7777        # baseUrl; portal/media URLs derive from it
#PORTAL_SERVICE_HOST_PORT=8085
#CHAT_FRONTEND_HOST_PORT=3000
#ADMIN_FRONTEND_HOST_PORT=3001
#ADMIN_SERVICE_HOST_PORT=8082
#UPLOAD_SERVICE_HOST_PORT=8086
#TCARD_SERVICE_HOST_PORT=8087
#SEARCH_SERVICE_HOST_PORT=19090
#
# Stack-wide settings.
#SITE_ID=site-local            # also drives ES index names, buckets, site URLs
#ALL_SITE_IDS=site-local
# Same-site room .event lanes: global|dual|local. Compose defaults to dual
# (both lanes); local mirrors the production end state. global breaks live
# delivery for crossSite:false rooms — the client subscribes chat.local.room.>.
#ROOM_SUBJECT_MODE=dual
#MONGO_URI=mongodb://mongodb:27017
#MONGO_DB=chat
#CASSANDRA_HOSTS=cassandra
#CASSANDRA_KEYSPACE=chat
#VALKEY_ADDRS=valkey:6379
#SEARCH_URL=http://elasticsearch:9200
#VAULT_ADDR=http://vault:8200
#VAULT_TOKEN=dev-only-token
#OIDC_ISSUER_URL=http://keycloak:8080/realms/chatapp
#OIDC_CLIENT_ID=nats-chat
#OIDC_AUDIENCES=nats-chat
#MINIO_ENDPOINT=minio:9000
#MINIO_ACCESS_KEY=minioadmin
#MINIO_SECRET_KEY=minioadmin
#BOOTSTRAP_STREAMS=true
#O11Y_ENABLED=true
#PPROF_ENABLED=false
EOF
chmod 600 "$ENV_FILE"

# chat-frontend/.env.local feeds `npm run dev` (Vite). Created on first run,
# left editable afterwards (e.g. point at staging) — new vars are appended.
if [ ! -f "$FRONTEND_ENV_FILE" ]; then
  cat > "$FRONTEND_ENV_FILE" <<EOF
VITE_PORTAL_URL=http://localhost:8085
EOF
elif ! grep -q '^VITE_PORTAL_URL=' "$FRONTEND_ENV_FILE"; then
  printf '\nVITE_PORTAL_URL=http://localhost:8085\n' >> "$FRONTEND_ENV_FILE"
fi

cat > "$NATS_CONF" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

port: 4222
http_port: 8222

operator: ${OPERATOR_JWT}

resolver: MEMORY

resolver_preload {
  ${ACCOUNT_PUB_KEY}: ${ACCOUNT_JWT}
  ${SYS_PUB_KEY}: ${SYS_JWT}
}

jetstream {
  store_dir: /data/jetstream
  max_mem: 1G
  max_file: 10G
}

websocket {
  port: 9222
  no_tls: true
}
EOF

echo "Wrote $NATS_CONF"
echo "Wrote $BACKEND_CREDS"
echo "Wrote $ENV_FILE"
echo "Wrote $FRONTEND_ENV_FILE (preserved if it already existed)"
echo ""

# --- Federated two-site NATS confs -------------------------------------------
# Same operator/account/SYS as the single-site conf above: gateway routing of
# JetStream publishes only works inside one account and one JS domain, so the
# two servers are one supercluster, not two independent deployments.
# No jetstream{domain} on either side — that shared domain is what lets
# site-local's outbox-worker publish chat.inbox.site-remote.external.* on its
# own local connection and have it land in INBOX-site-remote.
write_fed_nats_conf() {
  local site="$1" peer="$2" out="$3"
  cat > "$out" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

server_name: nats-${site}
port: 4222
http_port: 8222

operator: ${OPERATOR_JWT}

resolver: MEMORY

resolver_preload {
  ${ACCOUNT_PUB_KEY}: ${ACCOUNT_JWT}
  ${SYS_PUB_KEY}: ${SYS_JWT}
}

jetstream {
  store_dir: /data/jetstream
  max_mem: 1G
  max_file: 10G
}

websocket {
  port: 9222
  no_tls: true
}

cluster {
  name: ${site}
  port: 6222
}

gateway {
  name: ${site}
  port: 7222
  gateways: [
    { name: ${peer}, url: "nats://nats-${peer}:7222" }
  ]
}
EOF
}

write_fed_nats_conf site-local  site-remote "$SCRIPT_DIR/nats-site-local.conf"
write_fed_nats_conf site-remote site-local  "$SCRIPT_DIR/nats-site-remote.conf"
echo "Wrote $SCRIPT_DIR/nats-site-local.conf"
echo "Wrote $SCRIPT_DIR/nats-site-remote.conf"

# --- Federated two-site env files --------------------------------------------
# One file per site, loaded via --env-file by the fed-* make targets. Only the
# values that must differ are set; everything else falls through to the
# ${VAR:-default} defaults in the service compose files.
#
# ALL_SITE_IDS is identical on both sides — outbox-worker's federationPeers()
# drops the local site itself.
#
# Elasticsearch indexes and the MinIO bucket need no entries: search-service,
# search-sync-worker and upload-service already derive them from SITE_ID.
write_fed_env() {
  local site="$1" network="$2" mongo_db="$3" keyspace="$4" out="$5"
  shift 5
  cat > "$out" <<EOF
# Generated by docker-local/setup.sh — do not commit this file.
# Regenerate with: ./docker-local/setup.sh

AUTH_SCOPED_SIGNING_KEY=${AUTH_SK_SEED}
AUTH_ACCOUNT_PUB_KEY=${ACCOUNT_PUB_KEY}

NATS_URL=nats://nats:4222
NATS_CREDS_FILE=/etc/nats/backend.creds
DEV_MODE=true

SITE_ID=${site}
ALL_SITE_IDS=site-local,site-remote
CHAT_NETWORK=${network}
MONGO_DB=${mongo_db}
CASSANDRA_KEYSPACE=${keyspace}

# Distinguishes the two sites' spans in Tempo. Without it both sites'
# room-service spans carry identical resource attributes and a federated trace
# cannot be read.
OTEL_RESOURCE_ATTRIBUTES=site.id=${site}

# Site directory, identical on both sites: a client asks either portal and is
# told where its home site actually lives.
PORTAL_SITE_URLS={"site-local":{"baseUrl":"http://localhost:7777","natsUrl":"ws://localhost:9222"},"site-remote":{"baseUrl":"http://localhost:7877","natsUrl":"ws://localhost:9322"}}
CLUSTER_DOMAINS=[{"siteID":"site-local","domain":"http://localhost:7777"},{"siteID":"site-remote","domain":"http://localhost:7877"}]
$(printf '%s\n' "$@")
EOF
  chmod 600 "$out"
}

write_fed_env site-local chat-site-local chat chat "$SCRIPT_DIR/.env.site-local"

# site-remote takes a +100 host-port band. AUTH_SERVICE_HOST_PORT is the one
# exception (8080 -> 8190): 8180 is Keycloak.
write_fed_env site-remote chat-site-remote chat_remote chat_remote "$SCRIPT_DIR/.env.site-remote" \
  "CHAT_FRONTEND_HOST_PORT=3100" \
  "ADMIN_FRONTEND_HOST_PORT=3101" \
  "GATEWAY_HOST_PORT=7877" \
  "PORTAL_SERVICE_HOST_PORT=8185" \
  "AUTH_SERVICE_HOST_PORT=8190" \
  "ADMIN_SERVICE_HOST_PORT=8182" \
  "UPLOAD_SERVICE_HOST_PORT=8186" \
  "TCARD_SERVICE_HOST_PORT=8187" \
  "SEARCH_SERVICE_HOST_PORT=19190" \
  "PORTAL_URL=http://localhost:8185" \
  "CHAT_BASE_URL=http://localhost:3100"

echo "Wrote $SCRIPT_DIR/.env.site-local"
echo "Wrote $SCRIPT_DIR/.env.site-remote"
echo "=== Ready! ==="
echo ""
echo "  # Start all third-party deps (NATS, Mongo, Cassandra, ES, Keycloak)"
echo "  make deps-up"
echo ""
echo "  # Seed sample users/rooms/messages (needed to log in)"
echo "  make seed"
echo ""
echo "  # Start every microservice (foreground, streams logs)"
echo "  make up"
echo ""
echo "  # Start the browser UIs"
echo "  make ui-up"
echo ""
echo "  ──────────────────────────────────────"
echo "  chat-frontend:    http://localhost:3000"
echo "  admin-frontend:   http://localhost:3001"
echo "  API gateway:      http://localhost:7777  (baseUrl)"
echo "  portal-service:   http://localhost:8085"
echo "  NATS:             nats://localhost:4222"
echo "  NATS Monitoring:  http://localhost:8222"
echo "  NATS WebSocket:   ws://localhost:9222"
echo "  ──────────────────────────────────────"
echo ""
echo "  Log in as 'alice' (no password), or 'admin' / 'AdminDev123!'."
echo "  Full port map + troubleshooting: docker-local/README.md"
echo ""
