// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	models "github.com/hmchangw/chat/user-service/models"
	gomock "go.uber.org/mock/gomock"
)

// MocksubscriptionLister is a mock of subscriptionLister interface.
type MocksubscriptionLister struct {
	ctrl     *gomock.Controller
	recorder *MocksubscriptionListerMockRecorder
	isgomock struct{}
}

// MocksubscriptionListerMockRecorder is the mock recorder for MocksubscriptionLister.
type MocksubscriptionListerMockRecorder struct {
	mock *MocksubscriptionLister
}

// NewMocksubscriptionLister creates a new mock instance.
func NewMocksubscriptionLister(ctrl *gomock.Controller) *MocksubscriptionLister {
	mock := &MocksubscriptionLister{ctrl: ctrl}
	mock.recorder = &MocksubscriptionListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubscriptionLister) EXPECT() *MocksubscriptionListerMockRecorder {
	return m.recorder
}

// CountSubscriptionsFor mocks base method.
func (m *MocksubscriptionLister) CountSubscriptionsFor(ctx context.Context, account string, req models.CountRequest) (*models.CountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscriptionsFor", ctx, account, req)
	ret0, _ := ret[0].(*models.CountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscriptionsFor indicates an expected call of CountSubscriptionsFor.
func (mr *MocksubscriptionListerMockRecorder) CountSubscriptionsFor(ctx, account, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscriptionsFor", reflect.TypeOf((*MocksubscriptionLister)(nil).CountSubscriptionsFor), ctx, account, req)
}

// ListSubscriptionsFor mocks base method.
func (m *MocksubscriptionLister) ListSubscriptionsFor(ctx context.Context, account string, req models.SubscriptionListRequest, defaultLimit, maxLimit int) (*models.PagedSubscriptionListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptionsFor", ctx, account, req, defaultLimit, maxLimit)
	ret0, _ := ret[0].(*models.PagedSubscriptionListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptionsFor indicates an expected call of ListSubscriptionsFor.
func (mr *MocksubscriptionListerMockRecorder) ListSubscriptionsFor(ctx, account, req, defaultLimit, maxLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptionsFor", reflect.TypeOf((*MocksubscriptionLister)(nil).ListSubscriptionsFor), ctx, account, req, defaultLimit, maxLimit)
}
