// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/message-gatekeeper (interfaces: Store,ParentMessageFetcher)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store,ParentMessageFetcher
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	cassandra "github.com/hmchangw/chat/pkg/model/cassandra"
	roommetacache "github.com/hmchangw/chat/pkg/roommetacache"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetRoomMeta mocks base method.
func (m *MockStore) GetRoomMeta(ctx context.Context, roomID string) (roommetacache.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMeta", ctx, roomID)
	ret0, _ := ret[0].(roommetacache.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMeta indicates an expected call of GetRoomMeta.
func (mr *MockStoreMockRecorder) GetRoomMeta(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMeta", reflect.TypeOf((*MockStore)(nil).GetRoomMeta), ctx, roomID)
}

// GetSubscription mocks base method.
func (m *MockStore) GetSubscription(ctx context.Context, account, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, account, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockStoreMockRecorder) GetSubscription(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockStore)(nil).GetSubscription), ctx, account, roomID)
}

// ThreadRoomExists mocks base method.
func (m *MockStore) ThreadRoomExists(ctx context.Context, parentMessageID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ThreadRoomExists", ctx, parentMessageID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ThreadRoomExists indicates an expected call of ThreadRoomExists.
func (mr *MockStoreMockRecorder) ThreadRoomExists(ctx, parentMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ThreadRoomExists", reflect.TypeOf((*MockStore)(nil).ThreadRoomExists), ctx, parentMessageID)
}

// MockParentMessageFetcher is a mock of ParentMessageFetcher interface.
type MockParentMessageFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockParentMessageFetcherMockRecorder
	isgomock struct{}
}

// MockParentMessageFetcherMockRecorder is the mock recorder for MockParentMessageFetcher.
type MockParentMessageFetcherMockRecorder struct {
	mock *MockParentMessageFetcher
}

// NewMockParentMessageFetcher creates a new mock instance.
func NewMockParentMessageFetcher(ctrl *gomock.Controller) *MockParentMessageFetcher {
	mock := &MockParentMessageFetcher{ctrl: ctrl}
	mock.recorder = &MockParentMessageFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParentMessageFetcher) EXPECT() *MockParentMessageFetcherMockRecorder {
	return m.recorder
}

// FetchQuotedParent mocks base method.
func (m *MockParentMessageFetcher) FetchQuotedParent(ctx context.Context, account, roomID, siteID, messageID string) (*cassandra.QuotedParentMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchQuotedParent", ctx, account, roomID, siteID, messageID)
	ret0, _ := ret[0].(*cassandra.QuotedParentMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchQuotedParent indicates an expected call of FetchQuotedParent.
func (mr *MockParentMessageFetcherMockRecorder) FetchQuotedParent(ctx, account, roomID, siteID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchQuotedParent", reflect.TypeOf((*MockParentMessageFetcher)(nil).FetchQuotedParent), ctx, account, roomID, siteID, messageID)
}
