// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// QuitTeamsEmployees mocks base method.
func (m *MockStore) QuitTeamsEmployees(ctx context.Context, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QuitTeamsEmployees", ctx, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// QuitTeamsEmployees indicates an expected call of QuitTeamsEmployees.
func (mr *MockStoreMockRecorder) QuitTeamsEmployees(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QuitTeamsEmployees", reflect.TypeOf((*MockStore)(nil).QuitTeamsEmployees), ctx, accounts)
}

// UpsertEmployees mocks base method.
func (m *MockStore) UpsertEmployees(ctx context.Context, employees []model.EmployeeWithChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEmployees", ctx, employees)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEmployees indicates an expected call of UpsertEmployees.
func (mr *MockStoreMockRecorder) UpsertEmployees(ctx, employees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEmployees", reflect.TypeOf((*MockStore)(nil).UpsertEmployees), ctx, employees)
}

// UpsertUserIdentities mocks base method.
func (m *MockStore) UpsertUserIdentities(ctx context.Context, users []model.UserWithChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUserIdentities", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertUserIdentities indicates an expected call of UpsertUserIdentities.
func (mr *MockStoreMockRecorder) UpsertUserIdentities(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUserIdentities", reflect.TypeOf((*MockStore)(nil).UpsertUserIdentities), ctx, users)
}
