// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/tools/loadgen/internal/soak/send (interfaces: Lifecycle)
//
// Generated by this command:
//
//	mockgen -destination=mock_lifecycle_test.go -package=send . Lifecycle
//

// Package send is a generated GoMock package.
package send

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// AbandonUnsent mocks base method.
func (m *MockLifecycle) AbandonUnsent(arg0 *Pending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbandonUnsent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbandonUnsent indicates an expected call of AbandonUnsent.
func (mr *MockLifecycleMockRecorder) AbandonUnsent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbandonUnsent", reflect.TypeOf((*MockLifecycle)(nil).AbandonUnsent), arg0)
}

// Activate mocks base method.
func (m *MockLifecycle) Activate(arg0 *Pending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Activate", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Activate indicates an expected call of Activate.
func (mr *MockLifecycleMockRecorder) Activate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Activate", reflect.TypeOf((*MockLifecycle)(nil).Activate), arg0)
}

// Start mocks base method.
func (m *MockLifecycle) Start(arg0 *Pending) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockLifecycleMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLifecycle)(nil).Start), arg0)
}
