// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/broadcast-worker (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	roommetacache "github.com/hmchangw/chat/pkg/roommetacache"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AdvanceSubscriptionLastSeen mocks base method.
func (m *MockStore) AdvanceSubscriptionLastSeen(ctx context.Context, roomID, account string, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdvanceSubscriptionLastSeen", ctx, roomID, account, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdvanceSubscriptionLastSeen indicates an expected call of AdvanceSubscriptionLastSeen.
func (mr *MockStoreMockRecorder) AdvanceSubscriptionLastSeen(ctx, roomID, account, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdvanceSubscriptionLastSeen", reflect.TypeOf((*MockStore)(nil).AdvanceSubscriptionLastSeen), ctx, roomID, account, at)
}

// FilterRoomMembers mocks base method.
func (m *MockStore) FilterRoomMembers(ctx context.Context, roomID string, accounts []string) (map[string]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterRoomMembers", ctx, roomID, accounts)
	ret0, _ := ret[0].(map[string]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterRoomMembers indicates an expected call of FilterRoomMembers.
func (mr *MockStoreMockRecorder) FilterRoomMembers(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterRoomMembers", reflect.TypeOf((*MockStore)(nil).FilterRoomMembers), ctx, roomID, accounts)
}

// GetHistorySharedSince mocks base method.
func (m *MockStore) GetHistorySharedSince(ctx context.Context, roomID string, accounts []string) (map[string]*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, roomID, accounts)
	ret0, _ := ret[0].(map[string]*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockStoreMockRecorder) GetHistorySharedSince(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockStore)(nil).GetHistorySharedSince), ctx, roomID, accounts)
}

// GetRoom mocks base method.
func (m *MockStore) GetRoom(ctx context.Context, roomID string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockStoreMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockStore)(nil).GetRoom), ctx, roomID)
}

// GetRoomMeta mocks base method.
func (m *MockStore) GetRoomMeta(ctx context.Context, roomID string) (roommetacache.Meta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMeta", ctx, roomID)
	ret0, _ := ret[0].(roommetacache.Meta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMeta indicates an expected call of GetRoomMeta.
func (mr *MockStoreMockRecorder) GetRoomMeta(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMeta", reflect.TypeOf((*MockStore)(nil).GetRoomMeta), ctx, roomID)
}

// GetThreadFollowers mocks base method.
func (m *MockStore) GetThreadFollowers(ctx context.Context, parentMessageID string) (map[string]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadFollowers", ctx, parentMessageID)
	ret0, _ := ret[0].(map[string]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadFollowers indicates an expected call of GetThreadFollowers.
func (mr *MockStoreMockRecorder) GetThreadFollowers(ctx, parentMessageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadFollowers", reflect.TypeOf((*MockStore)(nil).GetThreadFollowers), ctx, parentMessageID)
}

// ListSubscriptions mocks base method.
func (m *MockStore) ListSubscriptions(ctx context.Context, roomID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", ctx, roomID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockStoreMockRecorder) ListSubscriptions(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockStore)(nil).ListSubscriptions), ctx, roomID)
}

// SetSubscriptionMentions mocks base method.
func (m *MockStore) SetSubscriptionMentions(ctx context.Context, roomID string, accounts []string, msgCreatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscriptionMentions", ctx, roomID, accounts, msgCreatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscriptionMentions indicates an expected call of SetSubscriptionMentions.
func (mr *MockStoreMockRecorder) SetSubscriptionMentions(ctx, roomID, accounts, msgCreatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscriptionMentions", reflect.TypeOf((*MockStore)(nil).SetSubscriptionMentions), ctx, roomID, accounts, msgCreatedAt)
}

// UpdateRoomLastMessage mocks base method.
func (m *MockStore) UpdateRoomLastMessage(ctx context.Context, roomID, msgID string, msgAt time.Time, mentionAll bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomLastMessage", ctx, roomID, msgID, msgAt, mentionAll)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomLastMessage indicates an expected call of UpdateRoomLastMessage.
func (mr *MockStoreMockRecorder) UpdateRoomLastMessage(ctx, roomID, msgID, msgAt, mentionAll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomLastMessage", reflect.TypeOf((*MockStore)(nil).UpdateRoomLastMessage), ctx, roomID, msgID, msgAt, mentionAll)
}
