// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/broadcast-worker (interfaces: RoomKeyProvider)
//
// Generated by this command:
//
//	mockgen -destination=mock_keystore_test.go -package=main . RoomKeyProvider
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	roomkeystore "github.com/hmchangw/chat/pkg/roomkeystore"
	gomock "go.uber.org/mock/gomock"
)

// MockRoomKeyProvider is a mock of RoomKeyProvider interface.
type MockRoomKeyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRoomKeyProviderMockRecorder
	isgomock struct{}
}

// MockRoomKeyProviderMockRecorder is the mock recorder for MockRoomKeyProvider.
type MockRoomKeyProviderMockRecorder struct {
	mock *MockRoomKeyProvider
}

// NewMockRoomKeyProvider creates a new mock instance.
func NewMockRoomKeyProvider(ctrl *gomock.Controller) *MockRoomKeyProvider {
	mock := &MockRoomKeyProvider{ctrl: ctrl}
	mock.recorder = &MockRoomKeyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomKeyProvider) EXPECT() *MockRoomKeyProviderMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRoomKeyProvider) Get(ctx context.Context, roomID string) (*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, roomID)
	ret0, _ := ret[0].(*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomKeyProviderMockRecorder) Get(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomKeyProvider)(nil).Get), ctx, roomID)
}

// SetIfAbsent mocks base method.
func (m *MockRoomKeyProvider) SetIfAbsent(ctx context.Context, roomID string, pair roomkeystore.RoomKeyPair) (*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIfAbsent", ctx, roomID, pair)
	ret0, _ := ret[0].(*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIfAbsent indicates an expected call of SetIfAbsent.
func (mr *MockRoomKeyProviderMockRecorder) SetIfAbsent(ctx, roomID, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIfAbsent", reflect.TypeOf((*MockRoomKeyProvider)(nil).SetIfAbsent), ctx, roomID, pair)
}
