// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/broadcast-worker (interfaces: Store)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . Store
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// GetRoom mocks base method.
func (m *MockStore) GetRoom(ctx context.Context, roomID string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockStoreMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockStore)(nil).GetRoom), ctx, roomID)
}

// ListSubscriptions mocks base method.
func (m *MockStore) ListSubscriptions(ctx context.Context, roomID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", ctx, roomID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockStoreMockRecorder) ListSubscriptions(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockStore)(nil).ListSubscriptions), ctx, roomID)
}

// SetSubscriptionMentions mocks base method.
func (m *MockStore) SetSubscriptionMentions(ctx context.Context, roomID string, accounts []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubscriptionMentions", ctx, roomID, accounts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSubscriptionMentions indicates an expected call of SetSubscriptionMentions.
func (mr *MockStoreMockRecorder) SetSubscriptionMentions(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubscriptionMentions", reflect.TypeOf((*MockStore)(nil).SetSubscriptionMentions), ctx, roomID, accounts)
}

// FetchAndUpdateRoom mocks base method.
func (m *MockStore) FetchAndUpdateRoom(ctx context.Context, roomID, msgID string, msgAt time.Time, mentionAll bool) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndUpdateRoom", ctx, roomID, msgID, msgAt, mentionAll)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAndUpdateRoom indicates an expected call of FetchAndUpdateRoom.
func (mr *MockStoreMockRecorder) FetchAndUpdateRoom(ctx, roomID, msgID, msgAt, mentionAll any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndUpdateRoom", reflect.TypeOf((*MockStore)(nil).FetchAndUpdateRoom), ctx, roomID, msgID, msgAt, mentionAll)
}
