// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/broadcast-worker (interfaces: LastMessageFetcher)
//
// Generated by this command:
//
//	mockgen -destination=mock_lastmsgfetcher_test.go -package=main . LastMessageFetcher
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLastMessageFetcher is a mock of LastMessageFetcher interface.
type MockLastMessageFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockLastMessageFetcherMockRecorder
	isgomock struct{}
}

// MockLastMessageFetcherMockRecorder is the mock recorder for MockLastMessageFetcher.
type MockLastMessageFetcherMockRecorder struct {
	mock *MockLastMessageFetcher
}

// NewMockLastMessageFetcher creates a new mock instance.
func NewMockLastMessageFetcher(ctrl *gomock.Controller) *MockLastMessageFetcher {
	mock := &MockLastMessageFetcher{ctrl: ctrl}
	mock.recorder = &MockLastMessageFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLastMessageFetcher) EXPECT() *MockLastMessageFetcherMockRecorder {
	return m.recorder
}

// FetchLastMessage mocks base method.
func (m *MockLastMessageFetcher) FetchLastMessage(ctx context.Context, roomID string, before time.Time) (*model.LastMessagePreview, *model.LastMessagePointer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchLastMessage", ctx, roomID, before)
	ret0, _ := ret[0].(*model.LastMessagePreview)
	ret1, _ := ret[1].(*model.LastMessagePointer)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FetchLastMessage indicates an expected call of FetchLastMessage.
func (mr *MockLastMessageFetcherMockRecorder) FetchLastMessage(ctx, roomID, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchLastMessage", reflect.TypeOf((*MockLastMessageFetcher)(nil).FetchLastMessage), ctx, roomID, before)
}
