// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	json "encoding/json"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchStore is a mock of SearchStore interface.
type MockSearchStore struct {
	ctrl     *gomock.Controller
	recorder *MockSearchStoreMockRecorder
	isgomock struct{}
}

// MockSearchStoreMockRecorder is the mock recorder for MockSearchStore.
type MockSearchStoreMockRecorder struct {
	mock *MockSearchStore
}

// NewMockSearchStore creates a new mock instance.
func NewMockSearchStore(ctrl *gomock.Controller) *MockSearchStore {
	mock := &MockSearchStore{ctrl: ctrl}
	mock.recorder = &MockSearchStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchStore) EXPECT() *MockSearchStoreMockRecorder {
	return m.recorder
}

// GetUserRoomDoc mocks base method.
func (m *MockSearchStore) GetUserRoomDoc(ctx context.Context, account string) (UserRoomDoc, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoomDoc", ctx, account)
	ret0, _ := ret[0].(UserRoomDoc)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserRoomDoc indicates an expected call of GetUserRoomDoc.
func (mr *MockSearchStoreMockRecorder) GetUserRoomDoc(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoomDoc", reflect.TypeOf((*MockSearchStore)(nil).GetUserRoomDoc), ctx, account)
}

// Search mocks base method.
func (m *MockSearchStore) Search(ctx context.Context, indices []string, body json.RawMessage) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, indices, body)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchStoreMockRecorder) Search(ctx, indices, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchStore)(nil).Search), ctx, indices, body)
}

// MockRestrictedRoomCache is a mock of RestrictedRoomCache interface.
type MockRestrictedRoomCache struct {
	ctrl     *gomock.Controller
	recorder *MockRestrictedRoomCacheMockRecorder
	isgomock struct{}
}

// MockRestrictedRoomCacheMockRecorder is the mock recorder for MockRestrictedRoomCache.
type MockRestrictedRoomCacheMockRecorder struct {
	mock *MockRestrictedRoomCache
}

// NewMockRestrictedRoomCache creates a new mock instance.
func NewMockRestrictedRoomCache(ctrl *gomock.Controller) *MockRestrictedRoomCache {
	mock := &MockRestrictedRoomCache{ctrl: ctrl}
	mock.recorder = &MockRestrictedRoomCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestrictedRoomCache) EXPECT() *MockRestrictedRoomCacheMockRecorder {
	return m.recorder
}

// GetRestricted mocks base method.
func (m *MockRestrictedRoomCache) GetRestricted(ctx context.Context, account string) (map[string]int64, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestricted", ctx, account)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRestricted indicates an expected call of GetRestricted.
func (mr *MockRestrictedRoomCacheMockRecorder) GetRestricted(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestricted", reflect.TypeOf((*MockRestrictedRoomCache)(nil).GetRestricted), ctx, account)
}

// SetRestricted mocks base method.
func (m *MockRestrictedRoomCache) SetRestricted(ctx context.Context, account string, rooms map[string]int64, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRestricted", ctx, account, rooms, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRestricted indicates an expected call of SetRestricted.
func (mr *MockRestrictedRoomCacheMockRecorder) SetRestricted(ctx, account, rooms, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRestricted", reflect.TypeOf((*MockRestrictedRoomCache)(nil).SetRestricted), ctx, account, rooms, ttl)
}

// MockMongoStore is a mock of MongoStore interface.
type MockMongoStore struct {
	ctrl     *gomock.Controller
	recorder *MockMongoStoreMockRecorder
	isgomock struct{}
}

// MockMongoStoreMockRecorder is the mock recorder for MockMongoStore.
type MockMongoStoreMockRecorder struct {
	mock *MockMongoStore
}

// NewMockMongoStore creates a new mock instance.
func NewMockMongoStore(ctrl *gomock.Controller) *MockMongoStore {
	mock := &MockMongoStore{ctrl: ctrl}
	mock.recorder = &MockMongoStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoStore) EXPECT() *MockMongoStoreMockRecorder {
	return m.recorder
}

// HydrateRooms mocks base method.
func (m *MockMongoStore) HydrateRooms(ctx context.Context, account string, roomIDs []string) ([]model.SearchRoom, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HydrateRooms", ctx, account, roomIDs)
	ret0, _ := ret[0].([]model.SearchRoom)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HydrateRooms indicates an expected call of HydrateRooms.
func (mr *MockMongoStoreMockRecorder) HydrateRooms(ctx, account, roomIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HydrateRooms", reflect.TypeOf((*MockMongoStore)(nil).HydrateRooms), ctx, account, roomIDs)
}

// SearchAppsByName mocks base method.
func (m *MockMongoStore) SearchAppsByName(ctx context.Context, query, account string, assistantEnabled *bool, offset, limit int) ([]model.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchAppsByName", ctx, query, account, assistantEnabled, offset, limit)
	ret0, _ := ret[0].([]model.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchAppsByName indicates an expected call of SearchAppsByName.
func (mr *MockMongoStoreMockRecorder) SearchAppsByName(ctx, query, account, assistantEnabled, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchAppsByName", reflect.TypeOf((*MockMongoStore)(nil).SearchAppsByName), ctx, query, account, assistantEnabled, offset, limit)
}

// MockSearchUsersClient is a mock of SearchUsersClient interface.
type MockSearchUsersClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearchUsersClientMockRecorder
	isgomock struct{}
}

// MockSearchUsersClientMockRecorder is the mock recorder for MockSearchUsersClient.
type MockSearchUsersClientMockRecorder struct {
	mock *MockSearchUsersClient
}

// NewMockSearchUsersClient creates a new mock instance.
func NewMockSearchUsersClient(ctrl *gomock.Controller) *MockSearchUsersClient {
	mock := &MockSearchUsersClient{ctrl: ctrl}
	mock.recorder = &MockSearchUsersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchUsersClient) EXPECT() *MockSearchUsersClientMockRecorder {
	return m.recorder
}

// SearchUsers mocks base method.
func (m *MockSearchUsersClient) SearchUsers(ctx context.Context, query string) ([]model.SearchUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, query)
	ret0, _ := ret[0].([]model.SearchUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockSearchUsersClientMockRecorder) SearchUsers(ctx, query any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockSearchUsersClient)(nil).SearchUsers), ctx, query)
}
