// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/history-service/internal/service (interfaces: MessageReader,MessageWriter,MessageRepository,SubscriptionRepository,RoomRepository,EventPublisher,ThreadRoomRepository,UserStore,CustomEmojiStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks . MessageReader,MessageWriter,MessageRepository,SubscriptionRepository,RoomRepository,EventPublisher,ThreadRoomRepository,UserStore,CustomEmojiStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cassrepo "github.com/hmchangw/chat/history-service/internal/cassrepo"
	models "github.com/hmchangw/chat/history-service/internal/models"
	model "github.com/hmchangw/chat/pkg/model"
	mongoutil "github.com/hmchangw/chat/pkg/mongoutil"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageReader is a mock of MessageReader interface.
type MockMessageReader struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReaderMockRecorder
	isgomock struct{}
}

// MockMessageReaderMockRecorder is the mock recorder for MockMessageReader.
type MockMessageReaderMockRecorder struct {
	mock *MockMessageReader
}

// NewMockMessageReader creates a new mock instance.
func NewMockMessageReader(ctrl *gomock.Controller) *MockMessageReader {
	mock := &MockMessageReader{ctrl: ctrl}
	mock.recorder = &MockMessageReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReader) EXPECT() *MockMessageReaderMockRecorder {
	return m.recorder
}

// GetAllMessagesAsc mocks base method.
func (m *MockMessageReader) GetAllMessagesAsc(ctx context.Context, roomID string, floor, ceiling time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesAsc", ctx, roomID, floor, ceiling, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesAsc indicates an expected call of GetAllMessagesAsc.
func (mr *MockMessageReaderMockRecorder) GetAllMessagesAsc(ctx, roomID, floor, ceiling, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesAsc", reflect.TypeOf((*MockMessageReader)(nil).GetAllMessagesAsc), ctx, roomID, floor, ceiling, pageReq)
}

// GetAllPinnedMessages mocks base method.
func (m *MockMessageReader) GetAllPinnedMessages(ctx context.Context, roomID string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPinnedMessages", ctx, roomID)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPinnedMessages indicates an expected call of GetAllPinnedMessages.
func (mr *MockMessageReaderMockRecorder) GetAllPinnedMessages(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPinnedMessages", reflect.TypeOf((*MockMessageReader)(nil).GetAllPinnedMessages), ctx, roomID)
}

// GetMessageByID mocks base method.
func (m *MockMessageReader) GetMessageByID(ctx context.Context, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageReaderMockRecorder) GetMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageReader)(nil).GetMessageByID), ctx, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageReader) GetMessagesAfter(ctx context.Context, roomID string, after, ceiling time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, ceiling, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageReaderMockRecorder) GetMessagesAfter(ctx, roomID, after, ceiling, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesAfter), ctx, roomID, after, ceiling, pageReq)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageReader) GetMessagesBefore(ctx context.Context, roomID string, before, floor time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, floor, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageReaderMockRecorder) GetMessagesBefore(ctx, roomID, before, floor, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesBefore), ctx, roomID, before, floor, pageReq)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageReader) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageReaderMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, pageReq)
}

// GetMessagesByIDs mocks base method.
func (m *MockMessageReader) GetMessagesByIDs(ctx context.Context, messageIDs []string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByIDs", ctx, messageIDs)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByIDs indicates an expected call of GetMessagesByIDs.
func (mr *MockMessageReaderMockRecorder) GetMessagesByIDs(ctx, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByIDs", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesByIDs), ctx, messageIDs)
}

// GetPinnedMessages mocks base method.
func (m *MockMessageReader) GetPinnedMessages(ctx context.Context, roomID string, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPinnedMessages", ctx, roomID, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPinnedMessages indicates an expected call of GetPinnedMessages.
func (mr *MockMessageReaderMockRecorder) GetPinnedMessages(ctx, roomID, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPinnedMessages", reflect.TypeOf((*MockMessageReader)(nil).GetPinnedMessages), ctx, roomID, pageReq)
}

// GetThreadMessages mocks base method.
func (m *MockMessageReader) GetThreadMessages(ctx context.Context, threadRoomID string, before, floor time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadMessages", ctx, threadRoomID, before, floor, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadMessages indicates an expected call of GetThreadMessages.
func (mr *MockMessageReaderMockRecorder) GetThreadMessages(ctx, threadRoomID, before, floor, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadMessages", reflect.TypeOf((*MockMessageReader)(nil).GetThreadMessages), ctx, threadRoomID, before, floor, pageReq)
}

// MockMessageWriter is a mock of MessageWriter interface.
type MockMessageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWriterMockRecorder
	isgomock struct{}
}

// MockMessageWriterMockRecorder is the mock recorder for MockMessageWriter.
type MockMessageWriterMockRecorder struct {
	mock *MockMessageWriter
}

// NewMockMessageWriter creates a new mock instance.
func NewMockMessageWriter(ctrl *gomock.Controller) *MockMessageWriter {
	mock := &MockMessageWriter{ctrl: ctrl}
	mock.recorder = &MockMessageWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageWriter) EXPECT() *MockMessageWriterMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockMessageWriter) AddReaction(ctx context.Context, msg *models.Message, key models.ReactionKey, reactor models.ReactorInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", ctx, msg, key, reactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockMessageWriterMockRecorder) AddReaction(ctx, msg, key, reactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockMessageWriter)(nil).AddReaction), ctx, msg, key, reactor)
}

// PinMessage mocks base method.
func (m *MockMessageWriter) PinMessage(ctx context.Context, msg *models.Message, pinnedAt time.Time, pinnedBy models.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMessage", ctx, msg, pinnedAt, pinnedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinMessage indicates an expected call of PinMessage.
func (mr *MockMessageWriterMockRecorder) PinMessage(ctx, msg, pinnedAt, pinnedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMessage", reflect.TypeOf((*MockMessageWriter)(nil).PinMessage), ctx, msg, pinnedAt, pinnedBy)
}

// RemoveReaction mocks base method.
func (m *MockMessageWriter) RemoveReaction(ctx context.Context, msg *models.Message, key models.ReactionKey, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", ctx, msg, key, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockMessageWriterMockRecorder) RemoveReaction(ctx, msg, key, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockMessageWriter)(nil).RemoveReaction), ctx, msg, key, updatedAt)
}

// SoftDeleteMessage mocks base method.
func (m *MockMessageWriter) SoftDeleteMessage(ctx context.Context, msg *models.Message, deletedAt time.Time) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMessage", ctx, msg, deletedAt)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SoftDeleteMessage indicates an expected call of SoftDeleteMessage.
func (mr *MockMessageWriterMockRecorder) SoftDeleteMessage(ctx, msg, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMessage", reflect.TypeOf((*MockMessageWriter)(nil).SoftDeleteMessage), ctx, msg, deletedAt)
}

// UnpinMessage mocks base method.
func (m *MockMessageWriter) UnpinMessage(ctx context.Context, msg *models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpinMessage indicates an expected call of UnpinMessage.
func (mr *MockMessageWriterMockRecorder) UnpinMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinMessage", reflect.TypeOf((*MockMessageWriter)(nil).UnpinMessage), ctx, msg)
}

// UpdateMessageContent mocks base method.
func (m *MockMessageWriter) UpdateMessageContent(ctx context.Context, msg *models.Message, newMsg string, editedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageContent", ctx, msg, newMsg, editedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageContent indicates an expected call of UpdateMessageContent.
func (mr *MockMessageWriterMockRecorder) UpdateMessageContent(ctx, msg, newMsg, editedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageContent", reflect.TypeOf((*MockMessageWriter)(nil).UpdateMessageContent), ctx, msg, newMsg, editedAt)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// AddReaction mocks base method.
func (m *MockMessageRepository) AddReaction(ctx context.Context, msg *models.Message, key models.ReactionKey, reactor models.ReactorInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReaction", ctx, msg, key, reactor)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReaction indicates an expected call of AddReaction.
func (mr *MockMessageRepositoryMockRecorder) AddReaction(ctx, msg, key, reactor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReaction", reflect.TypeOf((*MockMessageRepository)(nil).AddReaction), ctx, msg, key, reactor)
}

// GetAllMessagesAsc mocks base method.
func (m *MockMessageRepository) GetAllMessagesAsc(ctx context.Context, roomID string, floor, ceiling time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesAsc", ctx, roomID, floor, ceiling, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesAsc indicates an expected call of GetAllMessagesAsc.
func (mr *MockMessageRepositoryMockRecorder) GetAllMessagesAsc(ctx, roomID, floor, ceiling, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesAsc", reflect.TypeOf((*MockMessageRepository)(nil).GetAllMessagesAsc), ctx, roomID, floor, ceiling, pageReq)
}

// GetAllPinnedMessages mocks base method.
func (m *MockMessageRepository) GetAllPinnedMessages(ctx context.Context, roomID string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPinnedMessages", ctx, roomID)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPinnedMessages indicates an expected call of GetAllPinnedMessages.
func (mr *MockMessageRepositoryMockRecorder) GetAllPinnedMessages(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPinnedMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetAllPinnedMessages), ctx, roomID)
}

// GetMessageByID mocks base method.
func (m *MockMessageRepository) GetMessageByID(ctx context.Context, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageRepositoryMockRecorder) GetMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageByID), ctx, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageRepository) GetMessagesAfter(ctx context.Context, roomID string, after, ceiling time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, ceiling, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesAfter(ctx, roomID, after, ceiling, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesAfter), ctx, roomID, after, ceiling, pageReq)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, before, floor time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, floor, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBefore(ctx, roomID, before, floor, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBefore), ctx, roomID, before, floor, pageReq)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageRepository) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, pageReq)
}

// GetMessagesByIDs mocks base method.
func (m *MockMessageRepository) GetMessagesByIDs(ctx context.Context, messageIDs []string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByIDs", ctx, messageIDs)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByIDs indicates an expected call of GetMessagesByIDs.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesByIDs(ctx, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByIDs", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesByIDs), ctx, messageIDs)
}

// GetPinnedMessages mocks base method.
func (m *MockMessageRepository) GetPinnedMessages(ctx context.Context, roomID string, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPinnedMessages", ctx, roomID, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPinnedMessages indicates an expected call of GetPinnedMessages.
func (mr *MockMessageRepositoryMockRecorder) GetPinnedMessages(ctx, roomID, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPinnedMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetPinnedMessages), ctx, roomID, pageReq)
}

// GetThreadMessages mocks base method.
func (m *MockMessageRepository) GetThreadMessages(ctx context.Context, threadRoomID string, before, floor time.Time, pageReq cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadMessages", ctx, threadRoomID, before, floor, pageReq)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadMessages indicates an expected call of GetThreadMessages.
func (mr *MockMessageRepositoryMockRecorder) GetThreadMessages(ctx, threadRoomID, before, floor, pageReq any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetThreadMessages), ctx, threadRoomID, before, floor, pageReq)
}

// PinMessage mocks base method.
func (m *MockMessageRepository) PinMessage(ctx context.Context, msg *models.Message, pinnedAt time.Time, pinnedBy models.Participant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMessage", ctx, msg, pinnedAt, pinnedBy)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinMessage indicates an expected call of PinMessage.
func (mr *MockMessageRepositoryMockRecorder) PinMessage(ctx, msg, pinnedAt, pinnedBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMessage", reflect.TypeOf((*MockMessageRepository)(nil).PinMessage), ctx, msg, pinnedAt, pinnedBy)
}

// RemoveReaction mocks base method.
func (m *MockMessageRepository) RemoveReaction(ctx context.Context, msg *models.Message, key models.ReactionKey, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReaction", ctx, msg, key, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReaction indicates an expected call of RemoveReaction.
func (mr *MockMessageRepositoryMockRecorder) RemoveReaction(ctx, msg, key, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReaction", reflect.TypeOf((*MockMessageRepository)(nil).RemoveReaction), ctx, msg, key, updatedAt)
}

// SoftDeleteMessage mocks base method.
func (m *MockMessageRepository) SoftDeleteMessage(ctx context.Context, msg *models.Message, deletedAt time.Time) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMessage", ctx, msg, deletedAt)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SoftDeleteMessage indicates an expected call of SoftDeleteMessage.
func (mr *MockMessageRepositoryMockRecorder) SoftDeleteMessage(ctx, msg, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMessage", reflect.TypeOf((*MockMessageRepository)(nil).SoftDeleteMessage), ctx, msg, deletedAt)
}

// UnpinMessage mocks base method.
func (m *MockMessageRepository) UnpinMessage(ctx context.Context, msg *models.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinMessage", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpinMessage indicates an expected call of UnpinMessage.
func (mr *MockMessageRepositoryMockRecorder) UnpinMessage(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinMessage", reflect.TypeOf((*MockMessageRepository)(nil).UnpinMessage), ctx, msg)
}

// UpdateMessageContent mocks base method.
func (m *MockMessageRepository) UpdateMessageContent(ctx context.Context, msg *models.Message, newMsg string, editedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageContent", ctx, msg, newMsg, editedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageContent indicates an expected call of UpdateMessageContent.
func (mr *MockMessageRepositoryMockRecorder) UpdateMessageContent(ctx, msg, newMsg, editedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageContent", reflect.TypeOf((*MockMessageRepository)(nil).UpdateMessageContent), ctx, msg, newMsg, editedAt)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetHistorySharedSince mocks base method.
func (m *MockSubscriptionRepository) GetHistorySharedSince(ctx context.Context, account, roomID string) (*time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, account, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockSubscriptionRepositoryMockRecorder) GetHistorySharedSince(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetHistorySharedSince), ctx, account, roomID)
}

// GetSubscription mocks base method.
func (m *MockSubscriptionRepository) GetSubscription(ctx context.Context, account, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, account, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) GetSubscription(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetSubscription), ctx, account, roomID)
}

// MockRoomRepository is a mock of RoomRepository interface.
type MockRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockRoomRepositoryMockRecorder is the mock recorder for MockRoomRepository.
type MockRoomRepositoryMockRecorder struct {
	mock *MockRoomRepository
}

// NewMockRoomRepository creates a new mock instance.
func NewMockRoomRepository(ctrl *gomock.Controller) *MockRoomRepository {
	mock := &MockRoomRepository{ctrl: ctrl}
	mock.recorder = &MockRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomRepository) EXPECT() *MockRoomRepositoryMockRecorder {
	return m.recorder
}

// GetMinUserLastSeenAt mocks base method.
func (m *MockRoomRepository) GetMinUserLastSeenAt(ctx context.Context, roomID string) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinUserLastSeenAt", ctx, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinUserLastSeenAt indicates an expected call of GetMinUserLastSeenAt.
func (mr *MockRoomRepositoryMockRecorder) GetMinUserLastSeenAt(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinUserLastSeenAt", reflect.TypeOf((*MockRoomRepository)(nil).GetMinUserLastSeenAt), ctx, roomID)
}

// GetRoomTimes mocks base method.
func (m *MockRoomRepository) GetRoomTimes(ctx context.Context, roomID string) (time.Time, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomTimes", ctx, roomID)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRoomTimes indicates an expected call of GetRoomTimes.
func (mr *MockRoomRepositoryMockRecorder) GetRoomTimes(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomTimes", reflect.TypeOf((*MockRoomRepository)(nil).GetRoomTimes), ctx, roomID)
}

// GetRoomUserCount mocks base method.
func (m *MockRoomRepository) GetRoomUserCount(ctx context.Context, roomID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomUserCount", ctx, roomID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomUserCount indicates an expected call of GetRoomUserCount.
func (mr *MockRoomRepositoryMockRecorder) GetRoomUserCount(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomUserCount", reflect.TypeOf((*MockRoomRepository)(nil).GetRoomUserCount), ctx, roomID)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, subject string, data []byte, msgID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, data, msgID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, subject, data, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, subject, data, msgID)
}

// MockThreadRoomRepository is a mock of ThreadRoomRepository interface.
type MockThreadRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThreadRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockThreadRoomRepositoryMockRecorder is the mock recorder for MockThreadRoomRepository.
type MockThreadRoomRepositoryMockRecorder struct {
	mock *MockThreadRoomRepository
}

// NewMockThreadRoomRepository creates a new mock instance.
func NewMockThreadRoomRepository(ctrl *gomock.Controller) *MockThreadRoomRepository {
	mock := &MockThreadRoomRepository{ctrl: ctrl}
	mock.recorder = &MockThreadRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadRoomRepository) EXPECT() *MockThreadRoomRepositoryMockRecorder {
	return m.recorder
}

// GetFollowingThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetFollowingThreadRooms(ctx context.Context, roomID, account string, accessSince *time.Time, req mongoutil.OffsetPageRequest) (mongoutil.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingThreadRooms", ctx, roomID, account, accessSince, req)
	ret0, _ := ret[0].(mongoutil.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingThreadRooms indicates an expected call of GetFollowingThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetFollowingThreadRooms(ctx, roomID, account, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetFollowingThreadRooms), ctx, roomID, account, accessSince, req)
}

// GetThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetThreadRooms(ctx context.Context, roomID string, accessSince *time.Time, req mongoutil.OffsetPageRequest) (mongoutil.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadRooms", ctx, roomID, accessSince, req)
	ret0, _ := ret[0].(mongoutil.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadRooms indicates an expected call of GetThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetThreadRooms(ctx, roomID, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetThreadRooms), ctx, roomID, accessSince, req)
}

// GetUnreadThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetUnreadThreadRooms(ctx context.Context, roomID, account string, accessSince *time.Time, req mongoutil.OffsetPageRequest) (mongoutil.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadThreadRooms", ctx, roomID, account, accessSince, req)
	ret0, _ := ret[0].(mongoutil.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadThreadRooms indicates an expected call of GetUnreadThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetUnreadThreadRooms(ctx, roomID, account, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetUnreadThreadRooms), ctx, roomID, account, accessSince, req)
}

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// FindUsersByAccounts mocks base method.
func (m *MockUserStore) FindUsersByAccounts(ctx context.Context, accounts []string) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByAccounts", ctx, accounts)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByAccounts indicates an expected call of FindUsersByAccounts.
func (mr *MockUserStoreMockRecorder) FindUsersByAccounts(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByAccounts", reflect.TypeOf((*MockUserStore)(nil).FindUsersByAccounts), ctx, accounts)
}

// MockCustomEmojiStore is a mock of CustomEmojiStore interface.
type MockCustomEmojiStore struct {
	ctrl     *gomock.Controller
	recorder *MockCustomEmojiStoreMockRecorder
	isgomock struct{}
}

// MockCustomEmojiStoreMockRecorder is the mock recorder for MockCustomEmojiStore.
type MockCustomEmojiStoreMockRecorder struct {
	mock *MockCustomEmojiStore
}

// NewMockCustomEmojiStore creates a new mock instance.
func NewMockCustomEmojiStore(ctrl *gomock.Controller) *MockCustomEmojiStore {
	mock := &MockCustomEmojiStore{ctrl: ctrl}
	mock.recorder = &MockCustomEmojiStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomEmojiStore) EXPECT() *MockCustomEmojiStoreMockRecorder {
	return m.recorder
}

// CustomEmojiExists mocks base method.
func (m *MockCustomEmojiStore) CustomEmojiExists(ctx context.Context, siteID, shortcode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CustomEmojiExists", ctx, siteID, shortcode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CustomEmojiExists indicates an expected call of CustomEmojiExists.
func (mr *MockCustomEmojiStoreMockRecorder) CustomEmojiExists(ctx, siteID, shortcode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CustomEmojiExists", reflect.TypeOf((*MockCustomEmojiStore)(nil).CustomEmojiExists), ctx, siteID, shortcode)
}
