// Code generated by MockGen. DO NOT EDIT.
// Source: history-service/internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=history-service/internal/service/service.go -destination=history-service/internal/service/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cassrepo "github.com/hmchangw/chat/history-service/internal/cassrepo"
	models "github.com/hmchangw/chat/history-service/internal/models"
	mongorepo "github.com/hmchangw/chat/history-service/internal/mongorepo"
	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMessageReader is a mock of MessageReader interface.
type MockMessageReader struct {
	ctrl     *gomock.Controller
	recorder *MockMessageReaderMockRecorder
	isgomock struct{}
}

// MockMessageReaderMockRecorder is the mock recorder for MockMessageReader.
type MockMessageReaderMockRecorder struct {
	mock *MockMessageReader
}

// NewMockMessageReader creates a new mock instance.
func NewMockMessageReader(ctrl *gomock.Controller) *MockMessageReader {
	mock := &MockMessageReader{ctrl: ctrl}
	mock.recorder = &MockMessageReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageReader) EXPECT() *MockMessageReaderMockRecorder {
	return m.recorder
}

// GetAllMessagesAsc mocks base method.
func (m *MockMessageReader) GetAllMessagesAsc(ctx context.Context, roomID string, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesAsc", ctx, roomID, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesAsc indicates an expected call of GetAllMessagesAsc.
func (mr *MockMessageReaderMockRecorder) GetAllMessagesAsc(ctx, roomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesAsc", reflect.TypeOf((*MockMessageReader)(nil).GetAllMessagesAsc), ctx, roomID, q)
}

// GetMessageByID mocks base method.
func (m *MockMessageReader) GetMessageByID(ctx context.Context, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageReaderMockRecorder) GetMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageReader)(nil).GetMessageByID), ctx, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageReader) GetMessagesAfter(ctx context.Context, roomID string, after time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageReaderMockRecorder) GetMessagesAfter(ctx, roomID, after, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesAfter), ctx, roomID, after, q)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageReader) GetMessagesBefore(ctx context.Context, roomID string, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageReaderMockRecorder) GetMessagesBefore(ctx, roomID, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesBefore), ctx, roomID, before, q)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageReader) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageReaderMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, q)
}

// GetMessagesByIDs mocks base method.
func (m *MockMessageReader) GetMessagesByIDs(ctx context.Context, messageIDs []string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByIDs", ctx, messageIDs)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByIDs indicates an expected call of GetMessagesByIDs.
func (mr *MockMessageReaderMockRecorder) GetMessagesByIDs(ctx, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByIDs", reflect.TypeOf((*MockMessageReader)(nil).GetMessagesByIDs), ctx, messageIDs)
}

// GetThreadMessages mocks base method.
func (m *MockMessageReader) GetThreadMessages(ctx context.Context, roomID, threadRoomID string, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadMessages", ctx, roomID, threadRoomID, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadMessages indicates an expected call of GetThreadMessages.
func (mr *MockMessageReaderMockRecorder) GetThreadMessages(ctx, roomID, threadRoomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadMessages", reflect.TypeOf((*MockMessageReader)(nil).GetThreadMessages), ctx, roomID, threadRoomID, q)
}

// MockMessageWriter is a mock of MessageWriter interface.
type MockMessageWriter struct {
	ctrl     *gomock.Controller
	recorder *MockMessageWriterMockRecorder
	isgomock struct{}
}

// MockMessageWriterMockRecorder is the mock recorder for MockMessageWriter.
type MockMessageWriterMockRecorder struct {
	mock *MockMessageWriter
}

// NewMockMessageWriter creates a new mock instance.
func NewMockMessageWriter(ctrl *gomock.Controller) *MockMessageWriter {
	mock := &MockMessageWriter{ctrl: ctrl}
	mock.recorder = &MockMessageWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageWriter) EXPECT() *MockMessageWriterMockRecorder {
	return m.recorder
}

// SoftDeleteMessage mocks base method.
func (m *MockMessageWriter) SoftDeleteMessage(ctx context.Context, msg *models.Message, deletedAt time.Time) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMessage", ctx, msg, deletedAt)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SoftDeleteMessage indicates an expected call of SoftDeleteMessage.
func (mr *MockMessageWriterMockRecorder) SoftDeleteMessage(ctx, msg, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMessage", reflect.TypeOf((*MockMessageWriter)(nil).SoftDeleteMessage), ctx, msg, deletedAt)
}

// UpdateMessageContent mocks base method.
func (m *MockMessageWriter) UpdateMessageContent(ctx context.Context, msg *models.Message, newMsg string, editedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageContent", ctx, msg, newMsg, editedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageContent indicates an expected call of UpdateMessageContent.
func (mr *MockMessageWriterMockRecorder) UpdateMessageContent(ctx, msg, newMsg, editedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageContent", reflect.TypeOf((*MockMessageWriter)(nil).UpdateMessageContent), ctx, msg, newMsg, editedAt)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
	isgomock struct{}
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// GetAllMessagesAsc mocks base method.
func (m *MockMessageRepository) GetAllMessagesAsc(ctx context.Context, roomID string, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllMessagesAsc", ctx, roomID, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllMessagesAsc indicates an expected call of GetAllMessagesAsc.
func (mr *MockMessageRepositoryMockRecorder) GetAllMessagesAsc(ctx, roomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllMessagesAsc", reflect.TypeOf((*MockMessageRepository)(nil).GetAllMessagesAsc), ctx, roomID, q)
}

// GetMessageByID mocks base method.
func (m *MockMessageRepository) GetMessageByID(ctx context.Context, messageID string) (*models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageByID", ctx, messageID)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageByID indicates an expected call of GetMessageByID.
func (mr *MockMessageRepositoryMockRecorder) GetMessageByID(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageByID", reflect.TypeOf((*MockMessageRepository)(nil).GetMessageByID), ctx, messageID)
}

// GetMessagesAfter mocks base method.
func (m *MockMessageRepository) GetMessagesAfter(ctx context.Context, roomID string, after time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesAfter", ctx, roomID, after, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesAfter indicates an expected call of GetMessagesAfter.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesAfter(ctx, roomID, after, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesAfter", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesAfter), ctx, roomID, after, q)
}

// GetMessagesBefore mocks base method.
func (m *MockMessageRepository) GetMessagesBefore(ctx context.Context, roomID string, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBefore", ctx, roomID, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBefore indicates an expected call of GetMessagesBefore.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBefore(ctx, roomID, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBefore", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBefore), ctx, roomID, before, q)
}

// GetMessagesBetweenDesc mocks base method.
func (m *MockMessageRepository) GetMessagesBetweenDesc(ctx context.Context, roomID string, since, before time.Time, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesBetweenDesc", ctx, roomID, since, before, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesBetweenDesc indicates an expected call of GetMessagesBetweenDesc.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesBetweenDesc(ctx, roomID, since, before, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesBetweenDesc", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesBetweenDesc), ctx, roomID, since, before, q)
}

// GetMessagesByIDs mocks base method.
func (m *MockMessageRepository) GetMessagesByIDs(ctx context.Context, messageIDs []string) ([]models.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessagesByIDs", ctx, messageIDs)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessagesByIDs indicates an expected call of GetMessagesByIDs.
func (mr *MockMessageRepositoryMockRecorder) GetMessagesByIDs(ctx, messageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessagesByIDs", reflect.TypeOf((*MockMessageRepository)(nil).GetMessagesByIDs), ctx, messageIDs)
}

// GetThreadMessages mocks base method.
func (m *MockMessageRepository) GetThreadMessages(ctx context.Context, roomID, threadRoomID string, q cassrepo.PageRequest) (cassrepo.Page[models.Message], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadMessages", ctx, roomID, threadRoomID, q)
	ret0, _ := ret[0].(cassrepo.Page[models.Message])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadMessages indicates an expected call of GetThreadMessages.
func (mr *MockMessageRepositoryMockRecorder) GetThreadMessages(ctx, roomID, threadRoomID, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadMessages", reflect.TypeOf((*MockMessageRepository)(nil).GetThreadMessages), ctx, roomID, threadRoomID, q)
}

// SoftDeleteMessage mocks base method.
func (m *MockMessageRepository) SoftDeleteMessage(ctx context.Context, msg *models.Message, deletedAt time.Time) (time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteMessage", ctx, msg, deletedAt)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SoftDeleteMessage indicates an expected call of SoftDeleteMessage.
func (mr *MockMessageRepositoryMockRecorder) SoftDeleteMessage(ctx, msg, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteMessage", reflect.TypeOf((*MockMessageRepository)(nil).SoftDeleteMessage), ctx, msg, deletedAt)
}

// UpdateMessageContent mocks base method.
func (m *MockMessageRepository) UpdateMessageContent(ctx context.Context, msg *models.Message, newMsg string, editedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageContent", ctx, msg, newMsg, editedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageContent indicates an expected call of UpdateMessageContent.
func (mr *MockMessageRepositoryMockRecorder) UpdateMessageContent(ctx, msg, newMsg, editedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageContent", reflect.TypeOf((*MockMessageRepository)(nil).UpdateMessageContent), ctx, msg, newMsg, editedAt)
}

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// GetHistorySharedSince mocks base method.
func (m *MockSubscriptionRepository) GetHistorySharedSince(ctx context.Context, account, roomID string) (*time.Time, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySharedSince", ctx, account, roomID)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetHistorySharedSince indicates an expected call of GetHistorySharedSince.
func (mr *MockSubscriptionRepositoryMockRecorder) GetHistorySharedSince(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySharedSince", reflect.TypeOf((*MockSubscriptionRepository)(nil).GetHistorySharedSince), ctx, account, roomID)
}

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockEventPublisher) Publish(ctx context.Context, subject string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, subject, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockEventPublisherMockRecorder) Publish(ctx, subject, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockEventPublisher)(nil).Publish), ctx, subject, data)
}

// MockThreadRoomRepository is a mock of ThreadRoomRepository interface.
type MockThreadRoomRepository struct {
	ctrl     *gomock.Controller
	recorder *MockThreadRoomRepositoryMockRecorder
	isgomock struct{}
}

// MockThreadRoomRepositoryMockRecorder is the mock recorder for MockThreadRoomRepository.
type MockThreadRoomRepositoryMockRecorder struct {
	mock *MockThreadRoomRepository
}

// NewMockThreadRoomRepository creates a new mock instance.
func NewMockThreadRoomRepository(ctrl *gomock.Controller) *MockThreadRoomRepository {
	mock := &MockThreadRoomRepository{ctrl: ctrl}
	mock.recorder = &MockThreadRoomRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockThreadRoomRepository) EXPECT() *MockThreadRoomRepositoryMockRecorder {
	return m.recorder
}

// GetFollowingThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetFollowingThreadRooms(ctx context.Context, roomID, account string, accessSince *time.Time, req mongorepo.OffsetPageRequest) (mongorepo.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowingThreadRooms", ctx, roomID, account, accessSince, req)
	ret0, _ := ret[0].(mongorepo.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowingThreadRooms indicates an expected call of GetFollowingThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetFollowingThreadRooms(ctx, roomID, account, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowingThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetFollowingThreadRooms), ctx, roomID, account, accessSince, req)
}

// GetThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetThreadRooms(ctx context.Context, roomID string, accessSince *time.Time, req mongorepo.OffsetPageRequest) (mongorepo.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThreadRooms", ctx, roomID, accessSince, req)
	ret0, _ := ret[0].(mongorepo.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThreadRooms indicates an expected call of GetThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetThreadRooms(ctx, roomID, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetThreadRooms), ctx, roomID, accessSince, req)
}

// GetUnreadThreadRooms mocks base method.
func (m *MockThreadRoomRepository) GetUnreadThreadRooms(ctx context.Context, roomID, account string, accessSince *time.Time, req mongorepo.OffsetPageRequest) (mongorepo.OffsetPage[model.ThreadRoom], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadThreadRooms", ctx, roomID, account, accessSince, req)
	ret0, _ := ret[0].(mongorepo.OffsetPage[model.ThreadRoom])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadThreadRooms indicates an expected call of GetUnreadThreadRooms.
func (mr *MockThreadRoomRepositoryMockRecorder) GetUnreadThreadRooms(ctx, roomID, account, accessSince, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadThreadRooms", reflect.TypeOf((*MockThreadRoomRepository)(nil).GetUnreadThreadRooms), ctx, roomID, account, accessSince, req)
}
