// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/hmchangw/chat/room-worker (interfaces: SubscriptionStore,RoomKeyStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_store_test.go -package=main . SubscriptionStore,RoomKeyStore
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/hmchangw/chat/pkg/model"
	roomkeystore "github.com/hmchangw/chat/pkg/roomkeystore"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionStore is a mock of SubscriptionStore interface.
type MockSubscriptionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionStoreMockRecorder
	isgomock struct{}
}

// MockSubscriptionStoreMockRecorder is the mock recorder for MockSubscriptionStore.
type MockSubscriptionStoreMockRecorder struct {
	mock *MockSubscriptionStore
}

// NewMockSubscriptionStore creates a new mock instance.
func NewMockSubscriptionStore(ctrl *gomock.Controller) *MockSubscriptionStore {
	mock := &MockSubscriptionStore{ctrl: ctrl}
	mock.recorder = &MockSubscriptionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionStore) EXPECT() *MockSubscriptionStoreMockRecorder {
	return m.recorder
}

// ApplyMemberCountDelta mocks base method.
func (m *MockSubscriptionStore) ApplyMemberCountDelta(ctx context.Context, roomID string, userDelta, appDelta int, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyMemberCountDelta", ctx, roomID, userDelta, appDelta, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyMemberCountDelta indicates an expected call of ApplyMemberCountDelta.
func (mr *MockSubscriptionStoreMockRecorder) ApplyMemberCountDelta(ctx, roomID, userDelta, appDelta, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyMemberCountDelta", reflect.TypeOf((*MockSubscriptionStore)(nil).ApplyMemberCountDelta), ctx, roomID, userDelta, appDelta, ttl)
}

// BulkCreateRoomMembers mocks base method.
func (m *MockSubscriptionStore) BulkCreateRoomMembers(ctx context.Context, members []*model.RoomMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateRoomMembers", ctx, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreateRoomMembers indicates an expected call of BulkCreateRoomMembers.
func (mr *MockSubscriptionStoreMockRecorder) BulkCreateRoomMembers(ctx, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateRoomMembers", reflect.TypeOf((*MockSubscriptionStore)(nil).BulkCreateRoomMembers), ctx, members)
}

// BulkCreateSubscriptions mocks base method.
func (m *MockSubscriptionStore) BulkCreateSubscriptions(ctx context.Context, subs []*model.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreateSubscriptions", ctx, subs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreateSubscriptions indicates an expected call of BulkCreateSubscriptions.
func (mr *MockSubscriptionStoreMockRecorder) BulkCreateSubscriptions(ctx, subs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreateSubscriptions", reflect.TypeOf((*MockSubscriptionStore)(nil).BulkCreateSubscriptions), ctx, subs)
}

// CreateRoom mocks base method.
func (m *MockSubscriptionStore) CreateRoom(ctx context.Context, room *model.Room, key *roomkeystore.RoomKeyPair) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, room, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockSubscriptionStoreMockRecorder) CreateRoom(ctx, room, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockSubscriptionStore)(nil).CreateRoom), ctx, room, key)
}

// DeleteRoomMember mocks base method.
func (m *MockSubscriptionStore) DeleteRoomMember(ctx context.Context, roomID string, memberType model.RoomMemberType, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomMember", ctx, roomID, memberType, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomMember indicates an expected call of DeleteRoomMember.
func (mr *MockSubscriptionStoreMockRecorder) DeleteRoomMember(ctx, roomID, memberType, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomMember", reflect.TypeOf((*MockSubscriptionStore)(nil).DeleteRoomMember), ctx, roomID, memberType, memberID)
}

// DeleteSubscription mocks base method.
func (m *MockSubscriptionStore) DeleteSubscription(ctx context.Context, roomID, account string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", ctx, roomID, account)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockSubscriptionStoreMockRecorder) DeleteSubscription(ctx, roomID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockSubscriptionStore)(nil).DeleteSubscription), ctx, roomID, account)
}

// DeleteSubscriptionsByAccounts mocks base method.
func (m *MockSubscriptionStore) DeleteSubscriptionsByAccounts(ctx context.Context, roomID string, accounts []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscriptionsByAccounts", ctx, roomID, accounts)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSubscriptionsByAccounts indicates an expected call of DeleteSubscriptionsByAccounts.
func (mr *MockSubscriptionStoreMockRecorder) DeleteSubscriptionsByAccounts(ctx, roomID, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscriptionsByAccounts", reflect.TypeOf((*MockSubscriptionStore)(nil).DeleteSubscriptionsByAccounts), ctx, roomID, accounts)
}

// FindDMSubscriptionPair mocks base method.
func (m *MockSubscriptionStore) FindDMSubscriptionPair(ctx context.Context, roomID, requesterAccount string) (*model.Subscription, *model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDMSubscriptionPair", ctx, roomID, requesterAccount)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(*model.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindDMSubscriptionPair indicates an expected call of FindDMSubscriptionPair.
func (mr *MockSubscriptionStoreMockRecorder) FindDMSubscriptionPair(ctx, roomID, requesterAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDMSubscriptionPair", reflect.TypeOf((*MockSubscriptionStore)(nil).FindDMSubscriptionPair), ctx, roomID, requesterAccount)
}

// FindUsersByAccounts mocks base method.
func (m *MockSubscriptionStore) FindUsersByAccounts(ctx context.Context, accounts []string) ([]model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUsersByAccounts", ctx, accounts)
	ret0, _ := ret[0].([]model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUsersByAccounts indicates an expected call of FindUsersByAccounts.
func (mr *MockSubscriptionStoreMockRecorder) FindUsersByAccounts(ctx, accounts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUsersByAccounts", reflect.TypeOf((*MockSubscriptionStore)(nil).FindUsersByAccounts), ctx, accounts)
}

// GetApp mocks base method.
func (m *MockSubscriptionStore) GetApp(ctx context.Context, botAccount string) (*model.App, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetApp", ctx, botAccount)
	ret0, _ := ret[0].(*model.App)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetApp indicates an expected call of GetApp.
func (mr *MockSubscriptionStoreMockRecorder) GetApp(ctx, botAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetApp", reflect.TypeOf((*MockSubscriptionStore)(nil).GetApp), ctx, botAccount)
}

// GetOrgMembersWithIndividualStatus mocks base method.
func (m *MockSubscriptionStore) GetOrgMembersWithIndividualStatus(ctx context.Context, roomID, orgID string) ([]OrgMemberStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrgMembersWithIndividualStatus", ctx, roomID, orgID)
	ret0, _ := ret[0].([]OrgMemberStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrgMembersWithIndividualStatus indicates an expected call of GetOrgMembersWithIndividualStatus.
func (mr *MockSubscriptionStoreMockRecorder) GetOrgMembersWithIndividualStatus(ctx, roomID, orgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrgMembersWithIndividualStatus", reflect.TypeOf((*MockSubscriptionStore)(nil).GetOrgMembersWithIndividualStatus), ctx, roomID, orgID)
}

// GetRoom mocks base method.
func (m *MockSubscriptionStore) GetRoom(ctx context.Context, roomID string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockSubscriptionStoreMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockSubscriptionStore)(nil).GetRoom), ctx, roomID)
}

// GetRoomMeta mocks base method.
func (m *MockSubscriptionStore) GetRoomMeta(ctx context.Context, roomID string) (*model.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMeta", ctx, roomID)
	ret0, _ := ret[0].(*model.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMeta indicates an expected call of GetRoomMeta.
func (mr *MockSubscriptionStoreMockRecorder) GetRoomMeta(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMeta", reflect.TypeOf((*MockSubscriptionStore)(nil).GetRoomMeta), ctx, roomID)
}

// GetSubscription mocks base method.
func (m *MockSubscriptionStore) GetSubscription(ctx context.Context, account, roomID string) (*model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, account, roomID)
	ret0, _ := ret[0].(*model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockSubscriptionStoreMockRecorder) GetSubscription(ctx, account, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockSubscriptionStore)(nil).GetSubscription), ctx, account, roomID)
}

// GetSubscriptionAccounts mocks base method.
func (m *MockSubscriptionStore) GetSubscriptionAccounts(ctx context.Context, roomID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionAccounts", ctx, roomID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionAccounts indicates an expected call of GetSubscriptionAccounts.
func (mr *MockSubscriptionStoreMockRecorder) GetSubscriptionAccounts(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionAccounts", reflect.TypeOf((*MockSubscriptionStore)(nil).GetSubscriptionAccounts), ctx, roomID)
}

// GetUser mocks base method.
func (m *MockSubscriptionStore) GetUser(ctx context.Context, account string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, account)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockSubscriptionStoreMockRecorder) GetUser(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockSubscriptionStore)(nil).GetUser), ctx, account)
}

// GetUserWithMembership mocks base method.
func (m *MockSubscriptionStore) GetUserWithMembership(ctx context.Context, roomID, account string) (*UserWithMembership, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithMembership", ctx, roomID, account)
	ret0, _ := ret[0].(*UserWithMembership)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithMembership indicates an expected call of GetUserWithMembership.
func (mr *MockSubscriptionStoreMockRecorder) GetUserWithMembership(ctx, roomID, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithMembership", reflect.TypeOf((*MockSubscriptionStore)(nil).GetUserWithMembership), ctx, roomID, account)
}

// HasOrgRoomMembers mocks base method.
func (m *MockSubscriptionStore) HasOrgRoomMembers(ctx context.Context, roomID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasOrgRoomMembers", ctx, roomID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasOrgRoomMembers indicates an expected call of HasOrgRoomMembers.
func (mr *MockSubscriptionStoreMockRecorder) HasOrgRoomMembers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasOrgRoomMembers", reflect.TypeOf((*MockSubscriptionStore)(nil).HasOrgRoomMembers), ctx, roomID)
}

// ListAddMemberCandidates mocks base method.
func (m *MockSubscriptionStore) ListAddMemberCandidates(ctx context.Context, orgIDs, directAccounts []string, roomID string) ([]AddMemberCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAddMemberCandidates", ctx, orgIDs, directAccounts, roomID)
	ret0, _ := ret[0].([]AddMemberCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddMemberCandidates indicates an expected call of ListAddMemberCandidates.
func (mr *MockSubscriptionStoreMockRecorder) ListAddMemberCandidates(ctx, orgIDs, directAccounts, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddMemberCandidates", reflect.TypeOf((*MockSubscriptionStore)(nil).ListAddMemberCandidates), ctx, orgIDs, directAccounts, roomID)
}

// ListByRoom mocks base method.
func (m *MockSubscriptionStore) ListByRoom(ctx context.Context, roomID string) ([]model.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRoom", ctx, roomID)
	ret0, _ := ret[0].([]model.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRoom indicates an expected call of ListByRoom.
func (mr *MockSubscriptionStoreMockRecorder) ListByRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRoom", reflect.TypeOf((*MockSubscriptionStore)(nil).ListByRoom), ctx, roomID)
}

// ListNewMembersForNewRoom mocks base method.
func (m *MockSubscriptionStore) ListNewMembersForNewRoom(ctx context.Context, orgIDs, accounts []string, excludeAccount string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNewMembersForNewRoom", ctx, orgIDs, accounts, excludeAccount)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNewMembersForNewRoom indicates an expected call of ListNewMembersForNewRoom.
func (mr *MockSubscriptionStoreMockRecorder) ListNewMembersForNewRoom(ctx, orgIDs, accounts, excludeAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNewMembersForNewRoom", reflect.TypeOf((*MockSubscriptionStore)(nil).ListNewMembersForNewRoom), ctx, orgIDs, accounts, excludeAccount)
}

// ReconcileMemberCounts mocks base method.
func (m *MockSubscriptionStore) ReconcileMemberCounts(ctx context.Context, roomID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReconcileMemberCounts", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReconcileMemberCounts indicates an expected call of ReconcileMemberCounts.
func (mr *MockSubscriptionStoreMockRecorder) ReconcileMemberCounts(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReconcileMemberCounts", reflect.TypeOf((*MockSubscriptionStore)(nil).ReconcileMemberCounts), ctx, roomID)
}

// RemoveRole mocks base method.
func (m *MockSubscriptionStore) RemoveRole(ctx context.Context, account, roomID string, role model.Role) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, account, roomID, role)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockSubscriptionStoreMockRecorder) RemoveRole(ctx, account, roomID, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockSubscriptionStore)(nil).RemoveRole), ctx, account, roomID, role)
}

// UpdateRoomName mocks base method.
func (m *MockSubscriptionStore) UpdateRoomName(ctx context.Context, roomID, newName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoomName", ctx, roomID, newName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoomName indicates an expected call of UpdateRoomName.
func (mr *MockSubscriptionStoreMockRecorder) UpdateRoomName(ctx, roomID, newName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoomName", reflect.TypeOf((*MockSubscriptionStore)(nil).UpdateRoomName), ctx, roomID, newName)
}

// UpdateSubscriptionNamesForRoom mocks base method.
func (m *MockSubscriptionStore) UpdateSubscriptionNamesForRoom(ctx context.Context, roomID, newName string, nameUpdatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscriptionNamesForRoom", ctx, roomID, newName, nameUpdatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscriptionNamesForRoom indicates an expected call of UpdateSubscriptionNamesForRoom.
func (mr *MockSubscriptionStoreMockRecorder) UpdateSubscriptionNamesForRoom(ctx, roomID, newName, nameUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscriptionNamesForRoom", reflect.TypeOf((*MockSubscriptionStore)(nil).UpdateSubscriptionNamesForRoom), ctx, roomID, newName, nameUpdatedAt)
}

// MockRoomKeyStore is a mock of RoomKeyStore interface.
type MockRoomKeyStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomKeyStoreMockRecorder
	isgomock struct{}
}

// MockRoomKeyStoreMockRecorder is the mock recorder for MockRoomKeyStore.
type MockRoomKeyStoreMockRecorder struct {
	mock *MockRoomKeyStore
}

// NewMockRoomKeyStore creates a new mock instance.
func NewMockRoomKeyStore(ctrl *gomock.Controller) *MockRoomKeyStore {
	mock := &MockRoomKeyStore{ctrl: ctrl}
	mock.recorder = &MockRoomKeyStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomKeyStore) EXPECT() *MockRoomKeyStoreMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockRoomKeyStore) Get(ctx context.Context, roomID string) (*roomkeystore.VersionedKeyPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, roomID)
	ret0, _ := ret[0].(*roomkeystore.VersionedKeyPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRoomKeyStoreMockRecorder) Get(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRoomKeyStore)(nil).Get), ctx, roomID)
}

// Rotate mocks base method.
func (m *MockRoomKeyStore) Rotate(ctx context.Context, roomID string, newPair roomkeystore.RoomKeyPair) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rotate", ctx, roomID, newPair)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rotate indicates an expected call of Rotate.
func (mr *MockRoomKeyStoreMockRecorder) Rotate(ctx, roomID, newPair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rotate", reflect.TypeOf((*MockRoomKeyStore)(nil).Rotate), ctx, roomID, newPair)
}

// Set mocks base method.
func (m *MockRoomKeyStore) Set(ctx context.Context, roomID string, pair roomkeystore.RoomKeyPair) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, roomID, pair)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Set indicates an expected call of Set.
func (mr *MockRoomKeyStoreMockRecorder) Set(ctx, roomID, pair any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockRoomKeyStore)(nil).Set), ctx, roomID, pair)
}

// SetWithVersion mocks base method.
func (m *MockRoomKeyStore) SetWithVersion(ctx context.Context, roomID string, pair roomkeystore.RoomKeyPair, version int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithVersion", ctx, roomID, pair, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithVersion indicates an expected call of SetWithVersion.
func (mr *MockRoomKeyStoreMockRecorder) SetWithVersion(ctx, roomID, pair, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithVersion", reflect.TypeOf((*MockRoomKeyStore)(nil).SetWithVersion), ctx, roomID, pair, version)
}
