// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsChatStore is a mock of TeamsChatStore interface.
type MockTeamsChatStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsChatStoreMockRecorder
	isgomock struct{}
}

// MockTeamsChatStoreMockRecorder is the mock recorder for MockTeamsChatStore.
type MockTeamsChatStoreMockRecorder struct {
	mock *MockTeamsChatStore
}

// NewMockTeamsChatStore creates a new mock instance.
func NewMockTeamsChatStore(ctrl *gomock.Controller) *MockTeamsChatStore {
	mock := &MockTeamsChatStore{ctrl: ctrl}
	mock.recorder = &MockTeamsChatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsChatStore) EXPECT() *MockTeamsChatStoreMockRecorder {
	return m.recorder
}

// ListChatsNeedingRoom mocks base method.
func (m *MockTeamsChatStore) ListChatsNeedingRoom(ctx context.Context) ([]model.TeamsChat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatsNeedingRoom", ctx)
	ret0, _ := ret[0].([]model.TeamsChat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatsNeedingRoom indicates an expected call of ListChatsNeedingRoom.
func (mr *MockTeamsChatStoreMockRecorder) ListChatsNeedingRoom(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatsNeedingRoom", reflect.TypeOf((*MockTeamsChatStore)(nil).ListChatsNeedingRoom), ctx)
}

// MarkRoomsCreated mocks base method.
func (m *MockTeamsChatStore) MarkRoomsCreated(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRoomsCreated", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRoomsCreated indicates an expected call of MarkRoomsCreated.
func (mr *MockTeamsChatStoreMockRecorder) MarkRoomsCreated(ctx, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRoomsCreated", reflect.TypeOf((*MockTeamsChatStore)(nil).MarkRoomsCreated), ctx, ids)
}
