// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoomStore is a mock of RoomStore interface.
type MockRoomStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoomStoreMockRecorder
	isgomock struct{}
}

// MockRoomStoreMockRecorder is the mock recorder for MockRoomStore.
type MockRoomStoreMockRecorder struct {
	mock *MockRoomStore
}

// NewMockRoomStore creates a new mock instance.
func NewMockRoomStore(ctrl *gomock.Controller) *MockRoomStore {
	mock := &MockRoomStore{ctrl: ctrl}
	mock.recorder = &MockRoomStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoomStore) EXPECT() *MockRoomStoreMockRecorder {
	return m.recorder
}

// RoomStates mocks base method.
func (m *MockRoomStore) RoomStates(ctx context.Context, roomIDs []string) (map[string]RoomState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoomStates", ctx, roomIDs)
	ret0, _ := ret[0].(map[string]RoomState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoomStates indicates an expected call of RoomStates.
func (mr *MockRoomStoreMockRecorder) RoomStates(ctx, roomIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoomStates", reflect.TypeOf((*MockRoomStore)(nil).RoomStates), ctx, roomIDs)
}
