name: mock-user-service

services:
  mock-user-service:
    build:
      context: ../..
      dockerfile: mock-user-service/deploy/Dockerfile
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_CREDS_FILE=/etc/nats/backend.creds
      - SITE_ID=site-local
    volumes:
      - ../../docker-local/backend.creds:/etc/nats/backend.creds:ro
    networks:
      - chat-local

networks:
  chat-local:
    external: true
