package main

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseTable(t *testing.T) {
	tests := []struct {
		name    string
		input   string
		want    []method
		wantErr string
	}{
		{
			name: "comments and blank lines are skipped",
			input: "# a comment\n\nOpenRoom\topen_room\t\n" +
				"SetSSOToken\tset_sso_token\tG101\n",
			want: []method{
				{Constant: "OpenRoom", Value: "open_room"},
				{Constant: "SetSSOToken", Value: "set_sso_token", Suppress: "G101"},
			},
		},
		{
			name:  "a trailing suppression column may be omitted entirely",
			input: "OpenRoom\topen_room\n",
			want:  []method{{Constant: "OpenRoom", Value: "open_room"}},
		},
		{
			name:    "too many columns is an error",
			input:   "OpenRoom\topen_room\tG101\textra\n",
			wantErr: "expected 2 or 3 columns",
		},
		{
			name:    "a value outside snake_case is an error",
			input:   "OpenRoom\tOpenRoom\n",
			wantErr: "not verb-first snake_case",
		},
		{
			name:    "a constant outside PascalCase is an error",
			input:   "open_room\topen_room\n",
			wantErr: "not PascalCase",
		},
		{
			name:    "a duplicate value is an error",
			input:   "OpenRoom\topen_room\nReopenRoom\topen_room\n",
			wantErr: `duplicate label value "open_room"`,
		},
		{
			name:    "a duplicate constant is an error",
			input:   "OpenRoom\tclose_room\nOpenRoom\topen_room\n",
			wantErr: `duplicate constant "OpenRoom"`,
		},
		{
			name:    "an unknown suppression is an error",
			input:   "OpenRoom\topen_room\tG404\n",
			wantErr: `unsupported suppression "G404"`,
		},
		{
			name:    "rows out of label order are an error",
			input:   "OpenRoom\topen_room\nCloseRoom\tclose_room\n",
			wantErr: "out of order",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := parseTable(strings.NewReader(tt.input))
			if tt.wantErr != "" {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tt.wantErr)
				return
			}
			require.NoError(t, err)
			assert.Equal(t, tt.want, got)
		})
	}
}

func TestRender(t *testing.T) {
	out, err := render([]method{
		{Constant: "OpenRoom", Value: "open_room"},
		{Constant: "SetSSOToken", Value: "set_sso_token", Suppress: "G101"},
	})
	require.NoError(t, err)

	src := string(out)

	_, parseErr := parser.ParseFile(token.NewFileSet(), "rpcmethod_gen.go", src, parser.AllErrors)
	require.NoError(t, parseErr, "rendered source must parse:\n%s", src)

	// gofmt aligns runs of const specs, so assert against a whitespace-collapsed
	// copy rather than guessing how wide the padding ends up.
	flat := regexp.MustCompile(`[ \t]+`).ReplaceAllString(src, " ")

	assert.Contains(t, src, "// Code generated by tools/rpcmethodgen. DO NOT EDIT.")
	assert.Contains(t, src, "package natsmetrics")
	assert.Contains(t, flat, `MethodOpenRoom RPCMethod = "open_room"`)
	assert.Contains(t, flat, `MethodSetSSOToken RPCMethod = "set_sso_token"`)
	assert.Contains(t, flat, "rpcMethods = []RPCMethod{")
	assert.Contains(t, flat, " MethodOpenRoom,")
	assert.Contains(t, flat, " MethodSetSSOToken,")

	// The suppression must land immediately above the constant it covers: gosec
	// and semgrep both read the line directly above the statement, so a comment
	// one line off suppresses nothing and the sast gate goes red.
	lines := strings.Split(src, "\n")
	var nosecAt, constAt int
	for i, line := range lines {
		switch {
		case strings.Contains(line, "#nosec G101"):
			nosecAt = i
		case strings.Contains(line, `MethodSetSSOToken RPCMethod =`):
			constAt = i
		}
	}
	require.NotZero(t, nosecAt, "no gosec suppression rendered")
	assert.Contains(t, lines[nosecAt+1], "nosemgrep:",
		"each scanner reads its own directive, so both must be emitted")
	assert.Equal(t, constAt, nosecAt+2, "the suppression block must sit directly above the constant")

	assert.Equal(t, 1, strings.Count(src, "#nosec"), "only the G101 row may carry a suppression")
}

// TestRenderIsDeterministic keeps `make generate` from producing a spurious diff,
// which is what makes the up-to-date check in natsmetrics trustworthy.
func TestRenderIsDeterministic(t *testing.T) {
	in := []method{{Constant: "OpenRoom", Value: "open_room"}, {Constant: "PinMessage", Value: "pin_message"}}

	first, err := render(in)
	require.NoError(t, err)
	second, err := render(in)
	require.NoError(t, err)

	assert.Equal(t, string(first), string(second))
}

func TestRun(t *testing.T) {
	t.Run("writes a generated file from the table", func(t *testing.T) {
		dir := t.TempDir()
		in := filepath.Join(dir, "rpcmethods.tsv")
		out := filepath.Join(dir, "rpcmethod_gen.go")
		require.NoError(t, os.WriteFile(in, []byte("# header\nOpenRoom\topen_room\n"), 0o600))

		require.NoError(t, run(in, out))

		src, err := os.ReadFile(out)
		require.NoError(t, err)
		_, parseErr := parser.ParseFile(token.NewFileSet(), out, src, parser.AllErrors)
		require.NoError(t, parseErr)
		assert.Contains(t, string(src), `MethodOpenRoom RPCMethod = "open_room"`)
	})

	t.Run("reports a missing table", func(t *testing.T) {
		dir := t.TempDir()
		err := run(filepath.Join(dir, "absent.tsv"), filepath.Join(dir, "out.go"))
		require.Error(t, err)
		assert.Contains(t, err.Error(), "open")
	})

	t.Run("reports a malformed table and writes nothing", func(t *testing.T) {
		dir := t.TempDir()
		in := filepath.Join(dir, "rpcmethods.tsv")
		out := filepath.Join(dir, "rpcmethod_gen.go")
		require.NoError(t, os.WriteFile(in, []byte("open_room\topen_room\n"), 0o600))

		err := run(in, out)
		require.Error(t, err)
		assert.Contains(t, err.Error(), "not PascalCase")
		assert.NoFileExists(t, out, "a rejected table must not leave a partial file behind")
	})

	t.Run("reports an unwritable destination", func(t *testing.T) {
		dir := t.TempDir()
		in := filepath.Join(dir, "rpcmethods.tsv")
		require.NoError(t, os.WriteFile(in, []byte("OpenRoom\topen_room\n"), 0o600))

		err := run(in, filepath.Join(dir, "no-such-dir", "out.go"))
		require.Error(t, err)
		assert.Contains(t, err.Error(), "write")
	})
}
