// Code generated by MockGen. DO NOT EDIT.
// Source: store.go
//
// Generated by this command:
//
//	mockgen -source=store.go -destination=mock_store_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	model "github.com/hmchangw/chat/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsChatStore is a mock of TeamsChatStore interface.
type MockTeamsChatStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsChatStoreMockRecorder
	isgomock struct{}
}

// MockTeamsChatStoreMockRecorder is the mock recorder for MockTeamsChatStore.
type MockTeamsChatStoreMockRecorder struct {
	mock *MockTeamsChatStore
}

// NewMockTeamsChatStore creates a new mock instance.
func NewMockTeamsChatStore(ctrl *gomock.Controller) *MockTeamsChatStore {
	mock := &MockTeamsChatStore{ctrl: ctrl}
	mock.recorder = &MockTeamsChatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsChatStore) EXPECT() *MockTeamsChatStoreMockRecorder {
	return m.recorder
}

// ListChatsNeedingVerify mocks base method.
func (m *MockTeamsChatStore) ListChatsNeedingVerify(ctx context.Context) ([]model.TeamsChat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChatsNeedingVerify", ctx)
	ret0, _ := ret[0].([]model.TeamsChat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChatsNeedingVerify indicates an expected call of ListChatsNeedingVerify.
func (mr *MockTeamsChatStoreMockRecorder) ListChatsNeedingVerify(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChatsNeedingVerify", reflect.TypeOf((*MockTeamsChatStore)(nil).ListChatsNeedingVerify), ctx)
}

// MarkVerified mocks base method.
func (m *MockTeamsChatStore) MarkVerified(ctx context.Context, refs []VerifiedRef) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkVerified", ctx, refs)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkVerified indicates an expected call of MarkVerified.
func (mr *MockTeamsChatStoreMockRecorder) MarkVerified(ctx, refs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkVerified", reflect.TypeOf((*MockTeamsChatStore)(nil).MarkVerified), ctx, refs)
}
